### ISSUE TITLE
PyPardisoError - solver failed with error code -3

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1067]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

From a user: 
> I can create inventory using AB now but I cannot do LCA calculate with it. It shows error like this: 

@haasad, to me this looks related to https://github.com/haasad/PyPardisoProject/issues/36, could you have a look?

### Relevant errors

```python
(ASSB) C:\Users\shzg0001>activity-browser

-hiding tab:History

 

DevTools listening on ws://127.0.0.1:3999/devtools/browser/388d6c5e-6c1e-4e95-921d-1174c1f9dca2

-hiding tab:Activity Details

-hiding tab:Characterization Factors

-hiding tab:Graph Explorer

-hiding tab:LCA results

The Activity-Browser log file can be found at C:\Users\shzg0001\AppData\Local\ActivityBrowser\ActivityBrowser\Logs\ab_logs-2023-10-12_16-9-55.log

Loading user settings:

dirpath already loaded

Reset project settings directory to:C:\Users\shzg0001\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682

Loaded project:default

Brightway2 data directory: C:\Users\shzg0001\AppData\Local\pylca\Brightway3

Brightway2 active project: default

Qt Version:5.15.8

Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999

Reset project settings directory to:C:\Users\shzg0001\AppData\Local\pylca\Brightway3\ASSB.89f47fe0994b907cc0f581f99319deca

Reset metadata.

Loaded project:ASSB

Traceback (most recent call last):

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 62, in generate_setup

    new_tab = LCAResultsSubTab(data, self)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 113, in __init__

    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\activity_browser\bwutils\calculations.py", line 28, in do_LCA_calculations

    mlca = MLCA(cs_name)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\activity_browser\bwutils\multilca.py", line 144, in __init__

    self.lca.lci(factorize=True)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\bw2calc\lca.py", line 342, in lci

    self.lci_calculation()

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\bw2calc\lca.py", line 350, in lci_calculation

    self.supply_array = self.solve_linear_system()

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\bw2calc\lca.py", line 314, in solve_linear_system

    return self.solver(self.demand_array)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\pypardiso\scipy_aliases.py", line 46, in spsolve

    solver.factorize(A)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\pypardiso\pardiso_wrapper.py", line 155, in factorize

    self._call_pardiso(A, b)

  File "C:\Users\shzg0001\Anaconda3\envs\ASSB\lib\site-packages\pypardiso\pardiso_wrapper.py", line 286, in _call_pardiso

    raise PyPardisoError(pardiso_error.value)

pypardiso.pardiso_wrapper.PyPardisoError: The Pardiso solver failed with error code -3. See Pardiso documentation for details.
```

### Operating system

Windows 10

### Conda environment

```shell
(ASSB) C:\Users\shzg0001>conda list
# packages in environment at C:\Users\shzg0001\Anaconda3\envs\ASSB:
#
# Name                    Version                   Build  Channel
activity-browser          2.9.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
blinker                   1.6.3              pyhd8ed1ab_0    conda-forge
brightway2                2.4.4              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
brotlicffi                1.1.0.0          py39h99910a6_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.10             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
charset-normalizer        3.3.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py39h1f6ef14_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     3.0.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.43.1           py39ha55989b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.0               h12be248_0    conda-forge
glib-tools                2.78.0               h12be248_0    conda-forge
gst-plugins-base          1.22.6               h001b923_2    conda-forge
gstreamer                 1.22.6               hb4038d2_2    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib-resources       6.1.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
inflate64                 0.3.1            py39ha55989b_4    conda-forge
intel-openmp              2023.2.0         h57928b3_50496    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.15                 h67d730c_3    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_3    conda-forge
libclang13                15.0.7          default_h77d9078_3    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.0               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.43.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lxml                      4.9.3            py39h09808a7_0
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3            py39ha55989b_1    conda-forge
matplotlib-base           3.8.0            py39hf19769e_2    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.15          py39ha55989b_1    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numpy                     1.23.5           py39hbccbffa_0    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openpyxl                  3.1.2            py39ha55989b_1    conda-forge
openssl                   3.1.3                hcfcfb64_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.1            py39h32e6231_1    conda-forge
pathos                    0.3.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
peewee                    3.16.3           py39habf9222_1    conda-forge
pillow                    10.0.1           py39h368b509_2    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pox                       0.3.3              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.7            pyhd8ed1ab_0    conda-forge
psutil                    5.9.5            py39ha55989b_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.20.6             pyhd8ed1ab_0    conda-forge
pybcj                     1.0.1            py39ha55989b_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.19.0           py39ha55989b_1    conda-forge
pypardiso                 0.4.2              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.0.0            py39h99910a6_2    conda-forge
pyprind                   2.11.2          py39hcbf5309_1005    conda-forge
pyside2                   5.15.8           py39h56cbfbc_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.9           py39h95af829_1    conda-forge
qt-main                   5.15.8              h9e85ed6_17    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
salib                     1.4.7              pyhd8ed1ab_0    conda-forge
scipy                     1.11.3           py39hddb5d58_1    conda-forge
seaborn                   0.13.0               hd8ed1ab_0    conda-forge
seaborn-base              0.13.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stats_arrays              0.6.5              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0           py39hd88c2e4_2    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hcfcfb64_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
unidecode                 1.3.7              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.6              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
werkzeug                  3.0.0              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_8    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0           py39ha55989b_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.7              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipfile-deflate64         0.2.0            py39ha55989b_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by haasad** [comment]
```
(ASSB) C:\Users\shzg0001>conda list
# packages in environment at C:\Users\shzg0001\Anaconda3\envs\ASSB:
#
# Name                    Version                   Build  Channel
...
intel-openmp              2023.2.0         h57928b3_50496    conda-forge
...
mkl                       2020.4             hb70f87d_311    conda-forge
...
```
`mkl` is completely outdated, no idea why :man_shrugging: 

This could fix it:
```
conda install -c conda-forge mkl=2023.2
```

**Comment by marc-vdm** [comment]
> `mkl` is completely outdated, no idea why 🤷‍♂️

Yeah it's an env created today, weird.

I can confirm working with `mkl                       2022.1.0           h6a75c08_874    conda-forge` on my pc. 


@haasad  Should I pin `mkl >=2022.1.0`?

**Comment by haasad** [comment]
Then something is pretty broken in the dependency resolution :frowning_face: 

```
conda search --override-channels -c conda-forge "mkl>=2020" --subdir=win-64
Loading channels: done
# Name                       Version           Build  Channel             
mkl                           2020.2    h57928b3_256  conda-forge         
mkl                           2020.4    hb70f87d_311  conda-forge         
mkl                         2021.1.1     hb70f87d_71  conda-forge         
mkl                         2021.2.0    hb70f87d_389  conda-forge         
mkl                         2021.3.0    hb70f87d_564  conda-forge         
mkl                         2021.4.0    h0e2418a_729  conda-forge         
mkl                         2022.0.0    h0e2418a_796  conda-forge         
mkl                         2022.1.0    h6a75c08_874  conda-forge         
mkl                         2022.2.1  h6a75c08_19750  conda-forge         
mkl                         2022.2.1  h6a75c08_19751  conda-forge         
mkl                         2023.0.0  h6a75c08_25935  conda-forge         
mkl                         2023.0.0  h6a75c08_26647  conda-forge         
mkl                         2023.1.0  h6a75c08_46352  conda-forge         
mkl                         2023.1.0  h6a75c08_48682  conda-forge         
mkl                         2023.2.0     h6a75c08_39  conda-forge         
mkl                         2023.2.0     h6a75c08_40  conda-forge         
mkl                         2023.2.0     h6a75c08_41  conda-forge         
mkl                         2023.2.0     h6a75c08_42  conda-forge         
mkl                         2023.2.0     h6a75c08_43  conda-forge         
mkl                         2023.2.0  h6a75c08_49502  conda-forge         
mkl                         2023.2.0  h6a75c08_49503  conda-forge         
mkl                         2023.2.0  h6a75c08_49573  conda-forge         
mkl                         2023.2.0  h6a75c08_50496  conda-forge
```

Pinning to `mkl >=2022.1.0` alone won't fix the issue, because the major version of `mkl` and `intel-openmp` should match. mkl 2022 with openmp 2023 will probably still lead to errors.

I raised in issue upstream 1.5 years ago: https://github.com/conda-forge/intel_repack-feedstock/issues/33

Apparently this has recently been fixed. But I have no idea what the conda dependency resolver is doing.

**Comment by marc-vdm** [comment]
@haasad I'm now getting a user with the same issue as here, but installing the correct `mkl` version does not fix it':
This is their latest error and `conda list`:
![MicrosoftTeams-image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/bb57c930-3448-47a0-ab09-ce3b1032c4e7)

```shell
C:\Users\*>conda list
# packages in environment at C:\Users\*\.conda\envs\ab:
#
# Name                    Version                   Build  Channel
ab-plugin-scenariolink    0.0.4                    pypi_0    pypi
activity-browser          2.9.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0                   pypi_0    pypi
blinker                   1.6.3              pyhd8ed1ab_0    conda-forge
boto3                     1.28.63                  pypi_0    pypi
botocore                  1.31.63                  pypi_0    pypi
brightway2                2.4.4              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
brotlicffi                1.1.0.0          py39h99910a6_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.10             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.0              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
constructive-geometries   0.8.2                    pypi_0    pypi
contourpy                 1.1.1            py39h1f6ef14_1    conda-forge
country-converter         1.0.0                    pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
datapackage               1.15.2                   pypi_0    pypi
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     3.0.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.43.1           py39ha55989b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.0               h12be248_0    conda-forge
glib-tools                2.78.0               h12be248_0    conda-forge
greenlet                  3.0.0                    pypi_0    pypi
gst-plugins-base          1.22.6               h001b923_2    conda-forge
gstreamer                 1.22.6               hb4038d2_2    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
ijson                     3.2.3                    pypi_0    pypi
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib-resources       6.1.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
inflate64                 0.3.1            py39ha55989b_4    conda-forge
intel-openmp              2023.2.0         h57928b3_50496    conda-forge
isodate                   0.6.1                    pypi_0    pypi
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1                    pypi_0    pypi
jsonlines                 4.0.0                    pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.19.1                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 he9d350c_2    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              19_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              19_win64_mkl    conda-forge
libclang                  16.0.3          default_h8b4101f_1    conda-forge
libclang13                16.0.3          default_h45d3cf4_1    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.0               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_1    conda-forge
liblapack                 3.9.0              19_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.43.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                h4554b19_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
linear-tsv                1.1.0                    pypi_0    pypi
llvmlite                  0.41.0                   pypi_0    pypi
lxml                      4.9.2            py39h0942119_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3            py39ha55989b_1    conda-forge
matplotlib-base           3.8.0            py39hf19769e_2    conda-forge
mkl                       2023.2.0         h6a75c08_50496    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.15          py39ha55989b_1    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numba                     0.58.0                   pypi_0    pypi
numpy                     1.23.0                   pypi_0    pypi
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openpyxl                  3.1.2            py39ha55989b_1    conda-forge
openssl                   3.1.3                hcfcfb64_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.1            py39h32e6231_1    conda-forge
pathos                    0.3.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
peewee                    3.17.0           py39habf9222_0    conda-forge
pillow                    10.0.1           py39h6ef006c_1    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pox                       0.3.3              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.7            pyhd8ed1ab_0    conda-forge
prettytable               3.9.0                    pypi_0    pypi
psutil                    5.9.5            py39ha55989b_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.20.6             pyhd8ed1ab_0    conda-forge
pybcj                     1.0.1            py39ha55989b_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.19.0           py39ha55989b_1    conda-forge
pypardiso                 0.4.2              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.0.0            py39h99910a6_2    conda-forge
pyprind                   2.11.2          py39hcbf5309_1005    conda-forge
pyside2                   5.15.8           py39h56cbfbc_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzstd                    0.15.9           py39h95af829_1    conda-forge
qt-main                   5.15.8              h2c8576c_11    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
referencing               0.30.2                   pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3986                   2.0.0                    pypi_0    pypi
rpds-py                   0.10.6                   pypi_0    pypi
s3transfer                0.7.0                    pypi_0    pypi
salib                     1.4.7              pyhd8ed1ab_0    conda-forge
scipy                     1.11.3           py39hddb5d58_1    conda-forge
seaborn                   0.13.0               hd8ed1ab_0    conda-forge
seaborn-base              0.13.0             pyhd8ed1ab_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sparse                    0.14.0                   pypi_0    pypi
sqlalchemy                2.0.22                   pypi_0    pypi
stats_arrays              0.6.5              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.0           py39hd88c2e4_2    conda-forge
tableschema               1.20.2                   pypi_0    pypi
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tabulator                 1.53.5                   pypi_0    pypi
tbb                       2021.7.0             h91493d7_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hcfcfb64_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.14          pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unfold                    1.1.5                    pypi_0    pypi
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
unidecode                 1.3.7              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.17                  pypi_0    pypi
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wcwidth                   0.2.8                    pypi_0    pypi
werkzeug                  3.0.0              pyhd8ed1ab_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_8    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0           py39ha55989b_1    conda-forge
wurst                     0.3.4                    pypi_0    pypi
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.7              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipfile-deflate64         0.2.0            py39ha55989b_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by haasad** [comment]
hey @marc-vdm, looking at the output of `conda list`, it seems like the user installed stuff from `pypi` in their conda environment (i.e. something besides the AB was installed with `pip install`). While this usually isn't a problem per se, in this case `numpy` from conda-forge has been replaced by a numpy biuld from pypi. The conda-forge people put a great deal of effort into ensuring that all the numeric libraries play well together. But if you start mixing numeric libraries from pypi and conda-forge you sooner or later run into issues.

I'd suggest to create a new conda env from scratch. And if the users actually needs pypi stuff inside their AB env, then they need to try to install as many dependencies as possible from conda-forge and make sure that numpy and friends aren't overwritten (`pip install --no-deps` can be useful).

**Comment by marc-vdm** [comment]
Thanks a lot for the explanation! We have a new plugin ([ScenarioLink](https://github.com/polca/ScenarioLink)) that we allow installs on through both Conda and Pip.

@romainsacchi, (You only need to read the last 2 comments above this, not the whole thread) Do you think we can resolve this easily through modifying the dependencies of ScenarioLink and Unfold?

**Comment by haasad** [comment]
Is there any added benefit to have a package installable with `pip` in the context of an AB plugin? If not, I'd suggest to make the `conda` way the preferred and suggested installation method.

Debugging these hidden incompatibilities between the numeric libraries on three (or four with osx-arm) different architectures is a nightmare. And `conda-forge` conveniently makes sure that there shouldn't be any such incompatibilities.

**Comment by haasad** [comment]
Side note: If you install everything purely with `pip` there shouldn't be any issues either. We could check if there's still any roadblocks for making the AB accessible on PyPI. Back in the day, `MKL` was only available on `conda` and the AB was basically unusable without a fast solver (especially on windows). But `MKL` is now also available from `PyPI` since quite some time. I can't recall if there were any other issues (possibly Qt + PySide etc.)

**Comment by romainsacchi** [comment]
`ab-plugin-scenariolink` is installable from conda, as well as all its dependencies (including `unfold`). I did change the README of `ab-plugin-scenariolink` suggesting that installing from conda was preferred and installing from Pypi can create conflicts.
