### ISSUE TITLE
Cannot import 2 scenario difference files at the same time

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#1080]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

When I import the second file, it ignores its input and just uses the first file. 

### Relevant errors

```python
No data in scenario table 2, skipping
<function SuperstructureManager.check_scenario_exchange_values at 0x000001B16DB9C1F0> -- 0.0009996891021728516
<function SuperstructureManager.merge_flows_to_self at 0x000001B16DB90CA0> -- 0.004001140594482422
separator == ','
Loading Scenario file. This may take a while for large files
<function ScenarioImportWidget.scenario_db_check at 0x000001B172738CA0> -- 0.011996269226074219
<function SuperstructureManager.fill_empty_process_keys_in_exchanges at 0x000001B16DB90F70> -- 0.012003183364868164
<function SuperstructureManager.verify_scenario_process_keys at 0x000001B16DB9C0D0> -- 0.4853401184082031
<function SuperstructureManager.check_duplicates at 0x000001B16DB9C310> -- 0.06100749969482422
<function SuperstructureManager.check_duplicates at 0x000001B16DB9C310> -- 0.10201692581176758
<function SuperstructureManager.check_scenario_exchange_values at 0x000001B16DB9C1F0> -- 0.0020003318786621094
<function SuperstructureManager.check_scenario_exchange_values at 0x000001B16DB9C1F0> -- 0.01000213623046875
Traceback (most recent call last):
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\utils.py", line 69, in wrapper
    result = func(*args)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\layouts\tabs\LCA_setup.py", line 530, in load_action
    self.sync_superstructure(df)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\utils.py", line 69, in wrapper
    result = func(*args)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\layouts\tabs\LCA_setup.py", line 601, in sync_superstructure
    self._parent.combined_dataframe()
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\layouts\tabs\LCA_setup.py", line 380, in combined_dataframe
    self._scenario_dataframe = manager.combined_data(kind, skip_checks)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\manager.py", line 82, in combined_data
    df = SuperstructureManager.product_combine_frames(
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\manager.py", line 196, in product_combine_frames
    df = SuperstructureManager.merge_flows_to_self(df)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\utils.py", line 69, in wrapper
    result = func(*args)
  File "C:\Users\steub\Bernie\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\superstructure\manager.py", line 274, in merge_flows_to_self
    self_referential_production_flows.loc[prod_indexes, scenario_cols] \
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 885, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1893, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1928, in _setitem_with_indexer_split_path
    self._setitem_with_indexer_frame_value(indexer, value, name)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 2060, in _setitem_with_indexer_frame_value
    self._setitem_single_column(loc, val, pi)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 2095, in _setitem_single_column
    self.obj._mgr.column_setitem(loc, plane_indexer, value)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\internals\managers.py", line 1308, in column_setitem
    new_mgr = col_mgr.setitem((idx,), value)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\internals\managers.py", line 399, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\internals\managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\pandas\core\internals\blocks.py", line 1182, in setitem
    values[indexer] = casted
ValueError: shape mismatch: value array of shape (144,2) could not be broadcast to indexing result of shape (144,)

-hiding tab:LCA results
+showing tab:LCA results
```

### Operating system

Windows 10

**Comment by bsteubing** [comment]
it works correctly with version 2.7.5 of the AB
it does not work with version 2.9.0 and 2.9.1

**Comment by bsteubing** [comment]
@Zoophobus  could you try and see if you also have these issues and then see where it goes wrong? I think this has to do with the updates after 2.7.5

**Comment by Zoophobus** [comment]
So I have gone through this and have identified a problem with how the column indexes are used for assigning the values. Previously it was possible to have tuples (from a MultiIndex) combined with normal pandas string based indexes to be used in the assignment process. This seems to have been tidied up and now, from the error messages you provided here and those I received, in this case produces a vector of the tuple length to be assigned to the scalar values in the dataframe.

To avoid this I've changed how the combined column names are created and convert these to strings with parentheses grouping the different column index levels. This seems to be currently working, however, I want to run a few more examples before submitting this later today

**Comment by bsteubing** [comment]
Excellent - thanks so much for looking into this!

**Comment by bsteubing** [comment]
Closed with https://github.com/LCA-ActivityBrowser/activity-browser/pull/1083
