### ISSUE TITLE
Cannot open the AB

### ISSUE THREAD

**Issue by nethmisewwandi** [LCA-ActivityBrowser/activity-browser#1226]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Tried installing and uninstalling as well. Still cannot open the ab 

### Relevant errors

```python
(ab) C:\Users\kankanamgedonans>activity-browser
Traceback (most recent call last):
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\kankanamgedonans\.conda\envs\ab\lib\site-packages\activity_browser\__init__.py", line 9, in <module>
    from .application import Application
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\.conda\envs\ab\lib\site-packages\activity_browser\application.py", line 4, in <module>
    from .controllers import controllers
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\.conda\envs\ab\lib\site-packages\activity_browser\controllers\__init__.py", line 2, in <module>
    from .activity import ActivityController, ExchangeController
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\.conda\envs\ab\lib\site-packages\activity_browser\controllers\activity.py", line 5, in <module>
    import brightway2 as bw
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\.conda\envs\ab\lib\site-packages\brightway2\__init__.py", line 4, in <module>
    from bw2io import *
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\AppData\Roaming\Python\Python39\site-packages\bw2io\__init__.py", line 76, in <module>
    from .importers import (
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\AppData\Roaming\Python\Python39\site-packages\bw2io\importers\__init__.py", line 2, in <module>
    from .ecoinvent_lcia import EcoinventLCIAImporter
  File "C:\Users\kankanamgedonans\.conda\envs\ab\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\kankanamgedonans\AppData\Roaming\Python\Python39\site-packages\bw2io\importers\ecoinvent_lcia.py", line 19, in <module>
    class EcoinventLCIAImporter(LCIAImporter):
  File "C:\Users\kankanamgedonans\AppData\Roaming\Python\Python39\site-packages\bw2io\importers\ecoinvent_lcia.py", line 25, in EcoinventLCIAImporter
    def __init__(self, biosphere_database: str | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

(ab) C:\Users\kankanamgedonans>
```

### Operating system

Windows 10

### Conda environment

```shell
(ab) C:\Users\kankanamgedonans>conda list
# packages in environment at C:\Users\kankanamgedonans\.conda\envs\ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.9.5              pyhd8ed1ab_0    conda-forge
anyio                     4.2.0                    pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1                    pypi_0    pypi
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
boto3                     1.34.32                  pypi_0    pypi
botocore                  1.34.32                  pypi_0    pypi
bottleneck                1.3.7                    pypi_0    pypi
brightway2                2.4.4              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
brotlicffi                1.1.0.0          py39h99910a6_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.10             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.1                    pypi_0    pypi
console_shortcut          0.1.1                         4
constructive-geometries   0.8.2                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.2.0            py39h1f6ef14_0    conda-forge
country-converter         1.2                      pypi_0    pypi
cryptography              42.0.2                   pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
datapackage               1.15.2                   pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fastjsonschema            2.19.1                   pypi_0    pypi
flask                     3.0.2              pyhd8ed1ab_0    conda-forge
fonttools                 4.47.2           py39ha55989b_0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               hdaf720e_2    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.3               h12be248_0    conda-forge
glib-tools                2.78.3               h12be248_0    conda-forge
greenlet                  3.0.3                    pypi_0    pypi
gst-plugins-base          1.22.9               h001b923_0    conda-forge
gstreamer                 1.22.9               hb4038d2_0    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
ijson                     3.2.3                    pypi_0    pypi
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
inflate64                 1.0.0            py39ha55989b_0    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
ipykernel                 6.29.0                   pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
ipywidgets                8.1.1                    pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonlines                 4.0.0                    pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.7.1                    pypi_0    pypi
jupyter-events            0.9.0                    pypi_0    pypi
jupyter-lsp               2.2.2                    pypi_0    pypi
jupyter-server            2.12.5                   pypi_0    pypi
jupyter-server-terminals  0.5.2                    pypi_0    pypi
jupyterlab                4.0.12                   pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.25.2                   pypi_0    pypi
jupyterlab-widgets        3.0.9                    pypi_0    pypi
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 he9d350c_2    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libclang                  16.0.3          default_h8b4101f_1    conda-forge
libclang13                16.0.3          default_h45d3cf4_1    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.3               h16e383f_0    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_1    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.42               h19919ed_0    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                h4554b19_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
linear-tsv                1.1.0                    pypi_0    pypi
llvmlite                  0.42.0                   pypi_0    pypi
lxml                      4.9.2            py39h0942119_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.5            py39ha55989b_0    conda-forge
matplotlib-base           3.8.2            py39hf19769e_0    conda-forge
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mkl                       2024.0.0         h66d3029_49657    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.16          py39ha55989b_0    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.9.0                    pypi_0    pypi
nbconvert                 7.14.2                   pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
notebook                  7.0.7                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.59.0                   pypi_0    pypi
numpy                     1.23.0                   pypi_0    pypi
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openpyxl                  3.1.2            py39ha55989b_1    conda-forge
openssl                   3.2.1                hcfcfb64_0    conda-forge
overrides                 7.7.0                    pypi_0    pypi
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4            py39h32e6231_0    conda-forge
pandocfilters             1.5.1                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathos                    0.3.2              pyhd8ed1ab_1    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h17e33f8_0    conda-forge
peewee                    3.17.0           py39habf9222_0    conda-forge
pillow                    10.0.1           py39h6ef006c_1    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0                    pypi_0    pypi
pox                       0.3.4              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.8            pyhd8ed1ab_0    conda-forge
premise                   1.8.1                    pypi_0    pypi
premise-gwp               0.9.6                    pypi_0    pypi
prettytable               3.9.0                    pypi_0    pypi
prometheus-client         0.19.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.8            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py7zr                     0.20.8             pyhd8ed1ab_1    conda-forge
pyarrow                   15.0.0                   pypi_0    pypi
pybcj                     1.0.2            py39ha55989b_0    conda-forge
pycountry                 23.12.11                 pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.19.0           py39ha55989b_1    conda-forge
pygments                  2.17.2                   pypi_0    pypi
pypardiso                 0.4.3              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.1.0            py39h99910a6_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1005    conda-forge
pyside2                   5.15.8           py39h56cbfbc_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18          h4de0772_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306                      pypi_0    pypi
pywinpty                  2.0.12                   pypi_0    pypi
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
pyzstd                    0.15.9           py39h95af829_1    conda-forge
qt-main                   5.15.8              h2c8576c_11    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
qtconsole                 5.5.1                    pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
referencing               0.33.0                   pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986                   2.0.0                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
s3transfer                0.10.0                   pypi_0    pypi
salib                     1.4.7              pyhd8ed1ab_0    conda-forge
schema                    0.7.5                    pypi_0    pypi
scipy                     1.12.0           py39hddb5d58_2    conda-forge
seaborn                   0.13.2               hd8ed1ab_0    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2                    pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sparse                    0.15.1                   pypi_0    pypi
sqlalchemy                2.0.25                   pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
stats_arrays              0.6.6              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.1           py39hd88c2e4_0    conda-forge
tableschema               1.20.2                   pypi_0    pypi
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tabulator                 1.53.5                   pypi_0    pypi
tbb                       2021.7.0             h91493d7_0    conda-forge
terminado                 0.18.0                   pypi_0    pypi
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.1                   pypi_0    pypi
types-python-dateutil     2.8.19.20240106    pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
voluptuous                0.14.2             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
werkzeug                  3.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_8    conda-forge
widgetsnbextension        4.0.9                    pypi_0    pypi
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.16.0           py39ha55989b_0    conda-forge
wurst                     0.3.4                    pypi_0    pypi
xarray                    2024.1.1                 pypi_0    pypi
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.9              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipfile-deflate64         0.2.0            py39ha55989b_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge

(ab) C:\Users\kankanamgedonans>
```

**Comment by mrvisscher** [comment]
Hi!

Sorry to hear you're having problems. Looks to me that your environment is in bad shape, it is a good practice to not use packages from pypi in combination with those from conda. I'd like to ask you to reinstall activity-browser into a new environment or, if you don't need the old environment, clear and update it using the following command:

`conda create -n ab -c conda-forge --solver libmamba activity-browser`

If your problems persist, let me know!

Kind regards,

Marin

**Comment by nethmisewwandi** [comment]
Hey Marin!

Thought the same and deactivated the conda environment and redid everything again. My AB is up and running again just fine. Thanks!

Best,
Nethmi
