### ISSUE TITLE
Cannot load activity browser after updating from 2.7.0 to 2.9.7

### ISSUE THREAD

**Issue by desveauxj** [LCA-ActivityBrowser/activity-browser#1249]
### Updating AB

- [x] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

After updating the activity-browser from conda (2.7.0->2.9.7), I can no longer run activity-browser in the ab environment. As a note, I did update conda before updating activity-browser. I saw a similar issue #943, but the package issue in that instance looks to be the WebEngine whereas here the issue seems to be with the QtCore. Any ideas on fixes? 

### Relevant errors

```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\envs\ab\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\user\AppData\Local\anaconda3\envs\ab\lib\site-packages\activity_browser\__init__.py", line 6, in <module>
    from PySide2.QtCore import QSysInfo, __version__ as qt_version
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
```

### Operating system

Windows 10

### Conda environment

```shell
# packages in environment at C:\Users\user\AppData\Local\anaconda3\envs\ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.9.0                      py_0    bsteubing
aiofiles                  22.1.0           py39haa95532_0
aiosqlite                 0.18.0           py39haa95532_0
anyio                     3.5.0            py39haa95532_0
appdirs                   1.4.4              pyhd3eb1b0_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
arrow                     1.2.3            py39haa95532_1
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
asttokens                 2.0.5              pyhd3eb1b0_0
astunparse                1.6.3                      py_0
attrs                     23.1.0           py39haa95532_0
babel                     2.11.0           py39haa95532_0
backcall                  0.2.0              pyhd3eb1b0_0
beautifulsoup4            4.12.2           py39haa95532_0
bleach                    4.1.0              pyhd3eb1b0_0
brightway2                2.4.3              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
brotli-python             1.0.9            py39hd77b12b_7
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.7              pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h2bbff1b_5
ca-certificates           2023.12.12           haa95532_0
certifi                   2024.2.2         py39haa95532_0
cffi                      1.16.0           py39h2bbff1b_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7            py39haa95532_0
colorama                  0.4.6            py39haa95532_0
comm                      0.2.1            py39haa95532_0
contourpy                 1.2.0            py39h59b6b97_0
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.6.7            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
dill                      0.3.7            py39haa95532_0
docopt                    0.6.2            py39haa95532_1
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
entrypoints               0.4              py39haa95532_0
et_xmlfile                1.1.0            py39haa95532_0
exceptiongroup            1.2.0            py39haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
fasteners                 0.16.3             pyhd3eb1b0_0
flask                     2.2.5            py39haa95532_0
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.12.1               h546665d_1    conda-forge
future                    0.18.3           py39haa95532_0
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.4               hd77b12b_0
glib-tools                2.78.4               hd77b12b_0
gst-plugins-base          1.22.5               h001b923_0    conda-forge
gstreamer                 1.22.5               hb4038d2_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4              py39haa95532_0
importlib-metadata        7.0.1            py39haa95532_0
importlib_metadata        7.0.1                hd3eb1b0_0
importlib_resources       6.1.1            py39haa95532_1
inflate64                 0.3.1            py39h2bbff1b_1
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.25.0           py39h9909e9c_0
ipython                   8.15.0           py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
itsdangerous              2.0.1              pyhd3eb1b0_0
jedi                      0.18.1           py39haa95532_1
jinja2                    3.1.3            py39haa95532_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.19.2           py39haa95532_0
jsonschema-specifications 2023.7.1         py39haa95532_0
jupyter_client            7.4.9            py39haa95532_0
jupyter_core              5.5.0            py39haa95532_0
jupyter_events            0.8.0            py39haa95532_0
jupyter_server            1.23.4           py39haa95532_0
jupyter_server_fileid     0.9.0            py39haa95532_0
jupyter_server_ydoc       0.8.0            py39haa95532_1
jupyter_ydoc              0.2.4            py39haa95532_0
jupyterlab                3.6.3            py39haa95532_0
jupyterlab_pygments       0.2.2            py39haa95532_0
jupyterlab_server         2.25.1           py39haa95532_0
kiwisolver                1.4.4            py39hd77b12b_0
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_3    conda-forge
libclang13                15.0.7          default_h77d9078_3    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libffi                    3.4.4                hd77b12b_0
libglib                   2.78.4               ha17d25a_0
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libsqlite                 3.43.0               hcfcfb64_0    conda-forge
libtiff                   4.5.1                h6c8260b_1    conda-forge
libvorbis                 1.3.7                he774522_0
libwebp-base              1.3.2                h2bbff1b_0
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               h0ad7f3c_1
libxslt                   1.1.37               h2bbff1b_1
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lxml                      4.9.3            py39h09808a7_0
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3            py39h2bbff1b_0
matplotlib-base           3.8.0            py39h4ed8f06_0
matplotlib-inline         0.1.6            py39haa95532_0
mistune                   2.0.4            py39haa95532_0
mkl                       2022.1.0           h6a75c08_874    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.15          py39haa95532_0
multivolumefile           0.2.3              pyhd3eb1b0_0
munkres                   1.1.4                      py_0
nbclassic                 1.0.0            py39haa95532_0
nbclient                  0.8.0            py39haa95532_0
nbconvert                 7.10.0           py39haa95532_0
nbformat                  5.9.2            py39haa95532_0
nest-asyncio              1.6.0            py39haa95532_0
networkx                  3.1              py39haa95532_0
notebook                  6.5.4            py39haa95532_1
notebook-shim             0.2.3            py39haa95532_0
numpy                     1.23.5           py39hbccbffa_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.0.10           py39h2bbff1b_0
openssl                   3.1.2                hcfcfb64_0    conda-forge
packaging                 23.1             py39haa95532_0
pandas                    2.0.3            py39h1679cfb_1    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pcre2                     10.42                h0ff8eda_0
peewee                    3.16.3           py39habf9222_0    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    10.0.0           py39ha9166d5_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.3.1           py39haa95532_0
platformdirs              3.10.0           py39haa95532_0
pooch                     1.7.0            py39haa95532_0
prometheus_client         0.14.1           py39haa95532_0
prompt-toolkit            3.0.43           py39haa95532_0
psutil                    5.9.0            py39h2bbff1b_0
pthread-stubs             0.3                  h3c9f919_1
pure_eval                 0.2.2              pyhd3eb1b0_0
py7zr                     0.20.5           py39haa95532_0
pybcj                     1.0.1            py39h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pycryptodomex             3.15.0           py39h2bbff1b_0
pygments                  2.15.1           py39haa95532_1
pypardiso                 0.4.2              pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9            py39haa95532_0
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.0.0            py39hd77b12b_0
pyprind                   2.11.2          py39hcbf5309_1004    conda-forge
pyside2                   5.15.8           py39h56cbfbc_2    conda-forge
pysocks                   1.7.1            py39haa95532_0
python                    3.9.17          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-json-logger        2.0.7            py39haa95532_0
python-tzdata             2023.3             pyhd3eb1b0_0
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3.post1     py39haa95532_0
pywin32                   305              py39h2bbff1b_0
pywinpty                  2.0.10           py39h5da7b33_0
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1            py39h2bbff1b_0
pyzmq                     23.2.0           py39hd77b12b_0
pyzstd                    0.15.9           py39h95af829_0    conda-forge
qt-main                   5.15.8              he5a7383_16    conda-forge
qt-webengine              5.15.9               h5bd16bc_7
referencing               0.30.2           py39haa95532_0
requests                  2.31.0           py39haa95532_1
rfc3339-validator         0.1.4            py39haa95532_0
rfc3986-validator         0.1.1            py39haa95532_0
rpds-py                   0.10.6           py39h062c2fa_0
salib                     1.4.7            py39haa95532_0
scipy                     1.11.2           py39hde5eda1_0    conda-forge
seaborn                   0.12.2           py39haa95532_0
send2trash                1.8.2            py39haa95532_0
setuptools                68.2.2           py39haa95532_0
setuptools-scm            8.0.4            py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.3.0            py39haa95532_0
soupsieve                 2.5              py39haa95532_0
stack_data                0.2.0              pyhd3eb1b0_0
stats_arrays              0.6.5              pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0            py39haa95532_0
tbb                       2021.8.0             h59b6b97_0
terminado                 0.17.1           py39haa95532_0
texttable                 1.6.4              pyhd3eb1b0_0
tinycss2                  1.2.1            py39haa95532_0
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1            py39haa95532_0
tornado                   6.3.3            py39h2bbff1b_0
traitlets                 5.7.1            py39haa95532_0
typing-extensions         4.9.0            py39haa95532_1
typing_extensions         4.9.0            py39haa95532_1
tzdata                    2024a                h04d1e81_0
ucrt                      10.0.20348.0         haa95532_0
unicodecsv                0.14.1           py39haa95532_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   2.1.0            py39haa95532_1
vc                        14.2                 h21ff451_1
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
websocket-client          0.58.0           py39haa95532_4
werkzeug                  2.3.8            py39haa95532_0
wheel                     0.41.2           py39haa95532_0
whoosh                    2.7.4              pyhd3eb1b0_1
win_inet_pton             1.1.0            py39haa95532_0
winpty                    0.4.3                         4
wrapt                     1.14.1           py39h2bbff1b_0
xlrd                      2.0.1              pyhd3eb1b0_1
xlsxwriter                3.1.1            py39haa95532_0
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.4.6                h8cc25b3_0
y-py                      0.5.9            py39hb6bf4ef_0
yaml                      0.2.5                he774522_0
ypy-websocket             0.8.2            py39haa95532_0
zeromq                    4.3.4                hd77b12b_0
zipp                      3.17.0           py39haa95532_0
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by marc-vdm** [comment]
Hey, thanks for sharing this! We've changed the way AB is installed a while ago, as AB 2.7 is quite old, you need to go through a more extensive install process once, but afterwards, it will be easier. I've written a guide in #1049.

**Comment by desveauxj** [comment]
> Hey, thanks for sharing this! We've changed the way AB is installed a while ago, as AB 2.7 is quite old, you need to go through a more extensive install process once, but afterwards, it will be easier. I've written a guide in #1049.

Thank you very much for the quick reply and for linking that solution! Without being able to open the activity-browser to export my current database builds, is there a straightforward way to access them to move over to a fresh install?

**Comment by desveauxj** [comment]
Incredible, thank you for the quick reply and for passing along that guide. That did the trick!

**Comment by marc-vdm** [comment]
Happy it was resolved for you this easily :)
