### ISSUE TITLE
Scenarios calculation failed

### ISSUE THREAD

**Issue by shijie6688** [LCA-ActivityBrowser/activity-browser#1254]
### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

I got the following reminder when conducting the scenario calculation, how can I resolve it? Thanks a lot!

### Relevant errors

```python
DevTools listening on ws://127.0.0.1:3999/devtools/browser/aa2acc6c-53b0-453b-bd15-90949d79eefd
-hiding tab:Activity Details
-hiding tab:Characterization Factors
-hiding tab:Graph Explorer
-hiding tab:LCA results
The Activity Browser log file can be found at C:\Users\weisj\AppData\Local\ActivityBrowser\ActivityBrowser\Logs\ab_logs-2024-3-14_16-14-31.log
Activity Browser version: 2.9.7
Importing plugin ab_plugin_scenariolink
Loading user settings:
dirpath already loaded
Reset project settings directory to:C:\Users\weisj\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loaded project:default
Brightway2 data directory: C:\Users\weisj\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version:5.15.8
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Reset project settings directory to:C:\Users\weisj\AppData\Local\pylca\Brightway3\premise2.e546ef04a50e88517fdd6fbcd5c25640
Loaded tab ab_plugin_scenariolink
Reset metadata.
Loaded project:premise2
Loading Scenario file. This may take a while for large files
<function ScenarioImportWidget.scenario_db_check at 0x000001B991CC5CA0> -- 0.1238088607788086
<function SuperstructureManager.fill_empty_process_keys_in_exchanges at 0x000001B98F841940> -- 25.7911434173584
<function SuperstructureManager.verify_scenario_process_keys at 0x000001B98F841A60> -- 3.899717330932617
<function SuperstructureManager.check_duplicates at 0x000001B98F841CA0> -- 0.6093354225158691
<function SuperstructureManager.check_scenario_exchange_values at 0x000001B98F841B80> -- 0.46991944313049316
C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\bwutils\superstructure\manager.py:289: PerformanceWarning: indexing past lexsort depth may impact performance.
  self_referential_production_flows.loc[idx, 'flow type'] = 'production'
<function SuperstructureManager.merge_flows_to_self at 0x000001B98F841670> -- 14.820320844650269
<function ScenarioImportWidget.sync_superstructure at 0x000001B991CC5B80> -- 51.0708224773407
<function ScenarioImportWidget.load_action at 0x000001B991CC5A60> -- 437.1752133369446
Traceback (most recent call last):
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 62, in generate_setup
    new_tab = LCAResultsSubTab(data, self)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 113, in __init__
    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\bwutils\calculations.py", line 35, in do_LCA_calculations
    mlca = SuperstructureMLCA(cs_name, df)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\bwutils\superstructure\mlca.py", line 37, in __init__
    super().__init__(cs_name)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\activity_browser\bwutils\multilca.py", line 147, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\bw2calc\lca.py", line 342, in lci
    self.lci_calculation()
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\bw2calc\lca.py", line 350, in lci_calculation
    self.supply_array = self.solve_linear_system()
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\bw2calc\lca.py", line 314, in solve_linear_system
    return self.solver(self.demand_array)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\pypardiso\scipy_aliases.py", line 46, in spsolve
    solver.factorize(A)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\pypardiso\pardiso_wrapper.py", line 155, in factorize
    self._call_pardiso(A, b)
  File "C:\Users\weisj\Anaconda3\envs\ab_eco391\lib\site-packages\pypardiso\pardiso_wrapper.py", line 286, in _call_pardiso
    raise PyPardisoError(pardiso_error.value)
pypardiso.pardiso_wrapper.PyPardisoError: The Pardiso solver failed with error code -3. See Pardiso documentation for details.
```

### Operating system

Windows 10

### Conda environment

```shell
# Name                    Version                   Build  Channel
ab-plugin-scenariolink    0.0.3                    pypi_0    pypi
activity-browser          2.9.7              pyhd8ed1ab_0    conda-forge
anyio                     4.3.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39ha55989b_4    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   0.9.32             pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
boto3                     1.28.43                  pypi_0    pypi
botocore                  1.31.43                  pypi_0    pypi
bottleneck                1.3.7                    pypi_0    pypi
brightway2                2.4.4              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0            py39h99910a6_1    conda-forge
brotlicffi                1.1.0.0          py39h99910a6_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2            py39hcbf5309_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.7                    pypi_0    pypi
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py39ha55989b_0    conda-forge
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
console_shortcut          0.1.1                         4
constructive-geometries   0.8.2                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contourpy                 1.2.0            py39h1f6ef14_0    conda-forge
country-converter         1.0.0                    pypi_0    pypi
cryptography              41.0.3                   pypi_0    pypi
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
datapackage               1.15.2                   pypi_0    pypi
debugpy                   1.8.1            py39h99910a6_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.8              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     3.0.2              pyhd8ed1ab_0    conda-forge
fonttools                 4.49.0           py39ha55989b_0    conda-forge
fqdn                      1.5.1              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.80.0               h39d0aa6_0    conda-forge
glib-tools                2.80.0               h0a98069_0    conda-forge
greenlet                  2.0.2                    pypi_0    pypi
gst-plugins-base          1.22.9               h001b923_0    conda-forge
gstreamer                 1.22.9               hb4038d2_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0            py39hcbf5309_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.4              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
ijson                     3.2.3                    pypi_0    pypi
importlib-metadata        7.0.2              pyha770c72_0    conda-forge
importlib-resources       6.3.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.0.2                hd8ed1ab_0    conda-forge
importlib_resources       6.3.0              pyhd8ed1ab_0    conda-forge
inflate64                 1.0.0            py39ha55989b_1    conda-forge
intel-openmp              2024.0.0         h57928b3_49841    conda-forge
ipykernel                 6.29.3             pyha63f2e9_0    conda-forge
ipython                   8.15.0             pyh5737063_0    conda-forge
ipywidgets                8.1.2              pyhd8ed1ab_0    conda-forge
isodate                   0.6.1                    pypi_0    pypi
isoduration               20.11.0            pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1                    pypi_0    pypi
json5                     0.9.22             pyhd8ed1ab_0    conda-forge
jsonlines                 4.0.0                    pypi_0    pypi
jsonpointer               2.4              py39hcbf5309_3    conda-forge
jsonschema                4.21.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jsonschema-with-format-nongpl 4.21.1             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39hcbf5309_8    conda-forge
jupyter-lsp               2.2.4              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_console           6.6.3              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2            py39hcbf5309_0    conda-forge
jupyter_events            0.9.1              pyhd8ed1ab_0    conda-forge
jupyter_server            2.13.0             pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.1.4              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.25.4             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.10             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lcms2                     2.15                 h3e3b177_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              21_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              21_win64_mkl    conda-forge
libclang                  16.0.3          default_h8b4101f_1    conda-forge
libclang13                16.0.3          default_h45d3cf4_1    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.80.0               h39d0aa6_0    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_1    conda-forge
liblapack                 3.9.0              21_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libsqlite                 3.45.2               hcfcfb64_0    conda-forge
libtiff                   4.5.1                h6c8260b_1    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
linear-tsv                1.1.0                    pypi_0    pypi
llvmlite                  0.40.1                   pypi_0    pypi
lxml                      4.9.2            py39h0942119_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.5            py39ha55989b_0    conda-forge
matplotlib-base           3.8.3            py39hf19769e_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2024.0.0         h66d3029_49657    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.16          py39ha55989b_0    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.2             pyhd8ed1ab_0    conda-forge
nbconvert-core            7.16.2             pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.16.2             pyhd8ed1ab_0    conda-forge
nbformat                  5.10.2             pyhd8ed1ab_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
notebook                  7.0.3              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numba                     0.57.1                   pypi_0    pypi
numpy                     1.23.5           py39hbccbffa_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openpyxl                  3.1.2            py39ha55989b_1    conda-forge
openssl                   3.2.1                hcfcfb64_0    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3                    pypi_0    pypi
pandoc                    3.1.12.2             h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathos                    0.3.2              pyhd8ed1ab_1    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h17e33f8_0    conda-forge
peewee                    3.17.1           py39habf9222_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0           py39ha9166d5_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pox                       0.3.4              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.8            pyhd8ed1ab_0    conda-forge
premise                   1.6.7                    pypi_0    pypi
premise-gwp               0.9.6                    pypi_0    pypi
prettytable               3.8.0                    pypi_0    pypi
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
psutil                    5.9.8            py39ha55989b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py7zr                     0.21.0             pyhd8ed1ab_0    conda-forge
pyarrow                   13.0.0                   pypi_0    pypi
pybcj                     1.0.2            py39ha55989b_0    conda-forge
pycountry                 22.3.5                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.19.0           py39ha55989b_1    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.2              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.1.0            py39h99910a6_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1005    conda-forge
pyqt                      5.15.9           py39hb77abff_5    conda-forge
pyqt5-sip                 12.12.2          py39h99910a6_5    conda-forge
pyside2                   5.15.8           py39h56cbfbc_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.18          h4de0772_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306              py39h99910a6_2    conda-forge
pywinpty                  2.0.13           py39h99910a6_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1            py39ha55989b_1    conda-forge
pyzmq                     25.1.2           py39h7eaf5a6_0    conda-forge
pyzstd                    0.15.9           py39h95af829_1    conda-forge
qt-main                   5.15.8              h2c8576c_11    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
qtconsole                 5.5.1              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.5.1              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
referencing               0.33.0             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986                   2.0.0                    pypi_0    pypi
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rpds-py                   0.18.0           py39hf21820d_0    conda-forge
s3transfer                0.6.2                    pypi_0    pypi
salib                     1.4.8              pyhd8ed1ab_0    conda-forge
schema                    0.7.5                    pypi_0    pypi
scipy                     1.12.0           py39hddb5d58_2    conda-forge
seaborn                   0.13.2               hd8ed1ab_0    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.2              pyh08f2357_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
sip                       6.7.12           py39h99910a6_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sparse                    0.14.0                   pypi_0    pypi
sqlalchemy                2.0.20                   pypi_0    pypi
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
stats_arrays              0.6.6              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.1           py39hd88c2e4_0    conda-forge
tableschema               1.20.2                   pypi_0    pypi
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tabulator                 1.53.5                   pypi_0    pypi
tbb                       2021.7.0             h91493d7_0    conda-forge
terminado                 0.18.1             pyh5737063_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.4              py39ha55989b_0    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.20240311    pyhd8ed1ab_0    conda-forge
typing-extensions         4.10.0               hd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unfold                    1.1.1                    pypi_0    pypi
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
uri-template              1.3.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.16                  pypi_0    pypi
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
voluptuous                0.14.2             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webcolors                 1.13               pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.7.0              pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_8    conda-forge
widgetsnbextension        4.0.10             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.16.0           py39ha55989b_0    conda-forge
wurst                     0.3.3                    pypi_0    pypi
xarray                    2023.8.0                 pypi_0    pypi
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.9              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.5                h63175ca_1    conda-forge
zipfile-deflate64         0.2.0            py39ha55989b_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by haasad** [comment]
You're mixing dependencies from pypi and conda-forge  in the same conda environment, this can have unintended side-effects, see https://github.com/LCA-ActivityBrowser/activity-browser/issues/1067#issuecomment-1770661896 for more context.

I suggest you create a new environment and install the activity-browser and anything else you need from conda-forge. I'm confident this will fix your issue.

**Comment by haasad** [comment]
See also https://github.com/polca/ScenarioLink?tab=readme-ov-file#installation

**Comment by shijie6688** [comment]
I tried to install AB in a new environment, but can not succeed. As shown in below:

(ab_eco391_pure2) C:\Users\weisj>conda install conda-forge::activity-browser
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by mrvisscher** [comment]
Can you try to reinstall using the standard command? **Warning:** this will totally overwrite the original `ab` environment. Change  `ab` into something else if you don't mean to do this.
`conda create -n ab -c conda-forge --solver libmamba activity-browser`

**Comment by shijie6688** [comment]
> Can you try to reinstall using the standard command? **Warning:** this will totally overwrite the original `ab` environment. Change `ab` into something else if you don't mean to do this. `conda create -n ab -c conda-forge --solver libmamba activity-browser`

I have had an environment "ab" but I want to keep it. So can I change the command to "conda create -n ab_eco391_pure2 -c conda-forge --solver libmamba activity-browser"?

**Comment by mrvisscher** [comment]
Yes, that should work

**Comment by shijie6688** [comment]
Thank you both @haasad @mrvisscher for your answers. It works now!
