### ISSUE TITLE
Import error: cannot import name 'Retry Operational Error'

### ISSUE THREAD

**Issue by shubhankarupasani** [LCA-ActivityBrowser/activity-browser#131]
I am trying to get the activity browser up and running. The webpage opened earlier, but somehow is not opening again when I do the exact thing. 

I am running python 3.6 as it was mentioned as one of the caveats of the activity-browser, and I have installed the conda recipes from [here. 
](https://anaconda.org/haasad/pyqt)Below is the error I am getting. Please help
```(acb) C:\Users\Shubh>activity-browser
Traceback (most recent call last):
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\Scripts\activity-browser-script.py", line 5, in <module>
    from lca_activity_browser.app import run_activity_browser
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\lca_activity_browser\app\__init__.py", line 7, in <module>
    from .application import Application
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\lca_activity_browser\app\application.py", line 2, in <module>
    from .controller import Controller
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\lca_activity_browser\app\controller.py", line 6, in <module>
    import brightway2 as bw
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\brightway2\__init__.py", line 2, in <module>
    from bw2data import *
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\bw2data\__init__.py", line 33, in <module>
    from .project import projects
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\bw2data\project.py", line 8, in <module>
    from .sqlite import PickleField, create_database
  File "C:\Users\Shubh\AppData\Local\conda\conda\envs\acb\lib\site-packages\bw2data\sqlite.py", line 6, in <module>
    from playhouse.shortcuts import RetryOperationalError
ImportError: cannot import name 'RetryOperationalError'```

**Comment by haasad** [comment]
Hi,
this is related to #128. I will fix this today if I find the time. In the meantime you can install the [development version of the AB](https://github.com/LCA-ActivityBrowser/activity-browser#development-version).
```
conda uninstall activity-browser
conda install activity-browser-dev
```
Please let me know if this works for you and thanks for raising the issue :+1:

**Comment by haasad** [comment]
As of https://github.com/LCA-ActivityBrowser/activity-browser/commit/3af1f1d6387b60d6f14d277aa91f978f30da7f18, updating the AB should also do the trick:
```
conda update activity-browser
```

**Comment by shubhankarupasani** [comment]
Hi @haasad,

Thanks for the quick reply. It worked :)
