### ISSUE TITLE
Import wizard: 7zip dependency does not work properly

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#214]
When importing:
- downloading from ecoinvent works
**- unzipping throws an error**
- importing from unzipped data works fine

target dir: C:\Users\STEUBI~1\AppData\Local\Temp\tmp7ne1wixv
out path: C:/Users/steubingbrp/NO_BACKUP/v3.5/cutoff35.7z
['7za', 'x', 'C:/Users/steubingbrp/NO_BACKUP/v3.5/cutoff35.7z', '-oC:\\Users\\STEUBI~1\\AppData\\Local\\Temp\\tmp7ne1wixv']
Traceback (most recent call last):
  File "C:\Users\steubingbrp\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\ui\wizards\db_import_wizard.py", line 457, in run
    self.run_ecoinvent()
  File "C:\Users\steubingbrp\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\ui\wizards\db_import_wizard.py", line 472, in run_ecoinvent
    self.run_extract()
  File "C:\Users\steubingbrp\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\app\ui\wizards\db_import_wizard.py", line 508, in run_extract
    self.downloader.extract(target_dir=self.tempdir)
  File "C:\Users\steubingbrp\AppData\Local\Continuum\miniconda3\envs\py36\lib\site-packages\eidl\core.py", line 165, in extract
    self.extraction_process = subprocess.Popen(extract_cmd)
  File "C:\Users\steubingbrp\AppData\Local\Continuum\miniconda3\envs\py36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\steubingbrp\AppData\Local\Continuum\miniconda3\envs\py36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by haasad** [comment]
Any chance that it is still the same issue? -> Pycharm
https://github.com/haasad/EcoInventDownLoader/issues/14

**Comment by bsteubing** [comment]
True, very likely indeed - I'll check this...

**Comment by xiaoshir** [comment]
I also tried to import the 7zip file of ecoinvent 3.5 cutoff to the defalut project, but got this
![image](https://user-images.githubusercontent.com/28433916/53016321-a660d200-344d-11e9-8187-e352709eb80b.png) and then it just hanged there so I had to interrupt it.

**Comment by bsteubing** [comment]
Hi Shirley, I think this relates to #215 and should be solved by now. Three ways you can update to that code:
- update to the latest version of the development branch (https://github.com/LCA-ActivityBrowser/activity-browser#development-version)
- clone the master repository and run that
- add " *args, **kwargs" in the AB code as described in #215 
Hope this helps!
