### ISSUE TITLE
Removing database throws error

### ISSUE THREAD

**Issue by dgdekoning** [LCA-ActivityBrowser/activity-browser#235]
My suggestion in #234 to remove the databases can't be done from inside the activity-browser as trying to delete a database throws the error:

```bash
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\ab\lib\site-packages\activity_browser\app\controller.py", line 261, in delete_database
    project_settings.remove_db(name)
  File "C:\Users\user\AppData\Local\Continuum\miniconda3\envs\ab\lib\site-packages\activity_browser\app\settings.py", line 123, in remove_db
    self.settings['read-only-databases'].pop(db_name, None)
KeyError: 'read-only-databases'
```

According to @bsteubing this is similar to issue #194 and its linked pull-request https://github.com/LCA-ActivityBrowser/activity-browser/pull/199

**Comment by dgdekoning** [comment]
Looking deeper into the code, it looks like the 'read-only-databases' key is never stored when a project is created:

```python
# From activity_browser/app/settings.py lines 78 through 84
if os.path.isfile(self.settings_file):
    self.load_settings()
else:
    # make empty dict for settings
    self.settings = {}
    # save to ensure it's always accessible after first project select
    self.write_settings()
```
