### ISSUE TITLE
Aggregation fails under certain conditions

### ISSUE THREAD

**Issue by dgdekoning** [LCA-ActivityBrowser/activity-browser#331]
Something I noticed while putting together some simple calculation setups:
- When the calculation setup has a single functional unit and aggregation is attempted in `EF Contributions` or `Process Contributions` tab selecting aggregation options which use strings (`name`, `location`, `unit` `type` etc.) the Contributions class will fail during a conversion of `dict` to `pandas.DataFrame`, this explicitly does not occur when aggregating by categories (as these are tuples).

This likely has to do with how the dataframe converts processes dictionaries. So a likely solution is to either present the aggregated contribution data in a different way or to preprocess the data in some way when only a single functional unit (or method, likely) is present.

<details><summary>Error message</summary>
<p>

```python
...
+showing tab: LCA results
Traceback (most recent call last):
  File "C:\Users\koningdgde\workspace\activity-browser\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 743, in <lambda>
    lambda a: self.update_plot(aggregator=a))
  File "C:\Users\koningdgde\workspace\activity-browser\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 796, in update_plot
    self.df = self.update_dataframe()
  File "C:\Users\koningdgde\workspace\activity-browser\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 828, in update_dataframe
    limit_type=self.cutoff_menu.limit_type, normalize=self.relative)
  File "C:\Users\koningdgde\workspace\activity-browser\activity_browser\app\bwutils\multilca.py", line 609, in top_elementary_flow_contributions
    top_cont_dict, x_fields=x_fields, y_fields=self.act_fields, mask=mask)
  File "C:\Users\koningdgde\workspace\activity-browser\activity_browser\app\bwutils\multilca.py", line 445, in get_labelled_contribution_dict
    df = pd.DataFrame(cont_dict)
  File "C:\Users\koningdgde\AppData\Local\Continuum\miniconda3\envs\ab_dev\lib\site-packages\pandas\core\frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\koningdgde\AppData\Local\Continuum\miniconda3\envs\ab_dev\lib\site-packages\pandas\core\internals\construction.py", line 257, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\koningdgde\AppData\Local\Continuum\miniconda3\envs\ab_dev\lib\site-packages\pandas\core\internals\construction.py", line 77, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\koningdgde\AppData\Local\Continuum\miniconda3\envs\ab_dev\lib\site-packages\pandas\core\internals\construction.py", line 363, in extract_index
    index = _union_indexes(indexes, sort=not (compat.PY36 or have_ordered))
  File "C:\Users\koningdgde\AppData\Local\Continuum\miniconda3\envs\ab_dev\lib\site-packages\pandas\core\indexes\api.py", line 172, in _union_indexes
    result = Index(sorted(result))
TypeError: '<' not supported between instances of 'str' and 'tuple'
```

</p>
</details>

**Comment by dgdekoning** [comment]
A partial correction has been applied [here](https://github.com/LCA-ActivityBrowser/activity-browser/commit/51e073ec799a1b2c0c17a6776563c50b2802f420). A more robust solution should be implemented.
