### ISSUE TITLE
LCA Calculations does not work with only one FU 

### ISSUE THREAD

**Issue by cardosan** [LCA-ActivityBrowser/activity-browser#34]
As promised I start to contribute....or bother depending on the point of view :P

LCA Calculations does not work when only one FU is used (regardless of the number of methods), the prob does no occurs with more than one.
See error below

```python
Entering clear layout
Total: 0
Traceback (most recent call last):
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/lca_activity_browser/app/ui/tabs/lca_results.py", line 82, in calculate
    process_contribution_plot = LCAProcessContributionPlot(self, self.mlca)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/lca_activity_browser/app/ui/graphics.py", line 139, in __init__
    df_tc = pd.DataFrame(tc)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 6130, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 6173, in extract_index
    index = _union_indexes(indexes)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 67, in _union_indexes
    result = Index(sorted(result))
TypeError: '<' not supported between instances of 'tuple' and 'str'

Entering clear layout
Total: 0
Traceback (most recent call last):
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/lca_activity_browser/app/ui/tabs/lca_results.py", line 82, in calculate
    process_contribution_plot = LCAProcessContributionPlot(self, self.mlca)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/lca_activity_browser/app/ui/graphics.py", line 139, in __init__
    df_tc = pd.DataFrame(tc)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 6130, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/frame.py", line 6173, in extract_index
    index = _union_indexes(indexes)
  File "/home/giuseppec/miniconda3/envs/param/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 67, in _union_indexes
    result = Index(sorted(result))
TypeError: '<' not supported between instances of 'tuple' and 'str'
```

**Comment by haasad** [comment]
Fixed in #36, thanks for raising the issue!
