### ISSUE TITLE
Activity browser stopped working

### ISSUE THREAD

**Issue by ljlazar** [LCA-ActivityBrowser/activity-browser#429]
Hi,
I was able to start the ab one time and since then I get a "ValueError: unsupported pickle protocol: 5" and I am not able to fix it any more. Updating and reinstalling to another environment didn't solve the issue. I am very thankful for any advice.

`(ab2) C:\>activity-browser
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/49301bb0-a9fd-420f-b18a-594ee54a54dc
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\q\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Traceback (most recent call last):
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\ui\tables\projects.py", line 21, in sync
    self.project_names = sorted([project.name for project in projects])
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\ui\tables\projects.py", line 21, in <listcomp>
    self.project_names = sorted([project.name for project in projects])
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\bw2data\project.py", line 78, in __iter__
    for project_ds in ProjectDataset.select():
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 4196, in next
    self.cursor_wrapper.iterate()
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 4115, in iterate
    result = self.process_row(row)
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 7205, in process_row
    data = super(ModelObjectCursorWrapper, self).process_row(row)
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 7171, in process_row
    result[attr] = converters[i](row[i])
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\bw2data\sqlite.py", line 20, in python_value
    return pickle.loads(bytes(value))
ValueError: unsupported pickle protocol: 5
Reset metadata.
Loading user settings:
Traceback (most recent call last):
  File "C:\Users\q\Miniconda3\envs\ab2\Scripts\activity-browser-script.py", line 9, in <module>
    sys.exit(run_activity_browser())
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\__init__.py", line 14, in run_activity_browser
    application = Application()
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\application.py", line 9, in __init__
    self.controller = Controller()
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\controller.py", line 42, in __init__
    self.load_settings()
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\controller.py", line 97, in load_settings
    self.change_project(ab_settings.startup_project)
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\controller.py", line 157, in change_project
    elif name not in [p.name for p in bw.projects]:
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\activity_browser\app\controller.py", line 157, in <listcomp>
    elif name not in [p.name for p in bw.projects]:
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\bw2data\project.py", line 78, in __iter__
    for project_ds in ProjectDataset.select():
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 4196, in next
    self.cursor_wrapper.iterate()
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 4115, in iterate
    result = self.process_row(row)
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 7205, in process_row
    data = super(ModelObjectCursorWrapper, self).process_row(row)
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\peewee.py", line 7171, in process_row
    result[attr] = converters[i](row[i])
  File "C:\Users\q\Miniconda3\envs\ab2\lib\site-packages\bw2data\sqlite.py", line 20, in python_value
    return pickle.loads(bytes(value))
ValueError: unsupported pickle protocol: 5`

**Comment by dgdekoning** [comment]
Hey @ljlazar, this sounds similar to #388 can you check to see if the solution there works for you?

**Comment by ljlazar** [comment]
Thank you very much @dgdekoning for your help: switching to python 3.8 and the development version solved the issue.

**Comment by dgdekoning** [comment]
Glad to hear it @ljlazar!
