### ISSUE TITLE
Ecoinvent database importing macOS

### ISSUE THREAD

**Issue by matildedf** [LCA-ActivityBrowser/activity-browser#527]
Hi everyone,

I'm new to activity browser and unfortunately I have also small experience with Python.

I've installed correctly Activity Browser on my computer (MacOS) but when I try to import the Ecoinvent database on my terminal appears every time the error showed above and the importation is blocked. 
Is there someone that can help me solving this issue? 
Thank you in advice :) 

**System ERROR:
Unknown error: -2147024872
Traceback (most recent call last):
  File "/Applications/miniconda3/envs/ab/lib/python3.8/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 687, in run
    self.run_ecoinvent()
  File "/Applications/miniconda3/envs/ab/lib/python3.8/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 702, in run_ecoinvent
    self.run_import(dataset_dir)
  File "/Applications/miniconda3/envs/ab/lib/python3.8/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 763, in run_import
    importer = SingleOutputEcospold2Importer(
  File "/Applications/miniconda3/envs/ab/lib/python3.8/site-packages/bw2io/importers/ecospold2.py", line 67, in __init__
    self.data = extractor.extract(dirpath, db_name, use_mp=use_mp)
  File "/Applications/miniconda3/envs/ab/lib/python3.8/site-packages/activity_browser/app/ui/wizards/db_import_wizard.py", line 1123, in extract
    assert os.path.exists(dirpath), dirpath
AssertionError: /var/folders/ln/xv7q01px705fy9q_fp0l7zhh0000gn/T/tmpr3qfg9h7/datasets**

**Comment by dgdekoning** [comment]
I'm thinking this is a similar issue to [this](https://stackoverflow.com/questions/64494791/brightway-assertionerror-while-importing-ecoinvent-3-5). But given that it is MacOS, it might also be apple shenanigans.

**Comment by katjaettmayr** [comment]
I get the exact same error message when I try to import the Ecoinvent database (I am also using MacOS). Have you found a way to solve the problem meanwhile? :) 
<img width="571" alt="Bildschirmfoto 2021-03-08 um 08 52 34" src="https://user-images.githubusercontent.com/74415587/110290995-afe51480-7feb-11eb-8664-44eb02b9a973.png">
