### ISSUE TITLE
Excel Database import requires itself

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#587]
When I try to import an excel database, it wants to link to other databases, however, I have 2 databases that want to link to themselves (which is obviously impossible, as the database is not yet in AB). The excel file was exported from AB, so it should not contain user error?
This does not happen with all databases though, but I now do have 2 that give the error.
![error1](https://user-images.githubusercontent.com/34626062/115860674-5ca31600-a421-11eb-9c9f-d1807cbbdbb0.png)
![error2](https://user-images.githubusercontent.com/34626062/115860691-60cf3380-a421-11eb-86a4-fe15c1b02897.png)

I also get this as examples:
```
Could not link exchanges, here are 10 examples.:
[{'amount': 1.0,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 1.0,
  'location': 'GLO',
  'name': '100 Health and social work, EU27',
  'type': 'production',
  'uncertainty type': 0,
  'unit': 'EUR2003'},
 {'amount': 0.000165454230272282,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 0.000165454230272282,
  'location': 'GLO',
  'name': '101 Waste treatment, Incineration of waste, Food, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 0.000233938576998562,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 0.000233938576998562,
  'location': 'GLO',
  'name': '102 Waste treatment, Incineration of waste, Paper, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 0.000504451559403281,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 0.000504451559403281,
  'location': 'GLO',
  'name': '103 Waste treatment, Incineration of waste, Plastic, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 1.91387967653968e-05,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 1.91387967653968e-05,
  'location': 'GLO',
  'name': '104 Waste treatment, Incineration of waste, Metals, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 3.41019246897694e-05,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 3.41019246897694e-05,
  'location': 'inert, EU27',
  'name': '105 Waste treatment, Incineration of waste, Glass',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 0.000121819069080416,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 0.000121819069080416,
  'location': 'GLO',
  'name': '106 Waste treatment, Incineration of waste, Textiles, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 2.08289330654949e-05,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 2.08289330654949e-05,
  'location': 'GLO',
  'name': '107 Waste treatment, Incineration of waste, Wood, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 3.54526290661027e-05,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 3.54526290661027e-05,
  'location': 'Hazardous waste, EU27',
  'name': '108 Waste treatment, Incineration of waste, Oil',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'},
 {'amount': 3.06234261285084e-05,
  'categories': ('Input Output', 'EU27 2003'),
  'database': 'Forwast',
  'loc': 3.06234261285084e-05,
  'location': 'GLO',
  'name': '109 Waste treatment, Biogasification of food waste, EU27',
  'type': 'technosphere',
  'uncertainty type': 0,
  'unit': 'kilogram'}]
```

**Comment by CHarpprecht** [comment]
When we took a closer look at the soy and forwast database, we found that one of the processes, "101 waste treatment...", had itself as technosphere input. I think this is one part of the problem, not sure whether this alone can resolve the import issue though.

**Comment by marc-vdm** [comment]
Interesting pointer, I had a bit of a better look, and it indeed seems to be (part of) the issue.

When loading the exact same database as a .bw2package instead of excel, it loads without issue. 
It seems to me that the issue is with the excel importer (as the export is what is also in the .bw2package file) is failing to load processes that refer to themselves.

Additionally, running an LCA on this process that refers to itself does seem to break for me:

```
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/cc02b984-d07b-42df-8363-c5cf10ec7c30
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\m\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Reset metadata.
Loading user settings:
dirpath already loaded
Brightway2 data directory: C:\Users\m\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Reset project settings directory to: C:\Users\m\AppData\Local\pylca\Brightway3\soy_test.bef549d12c0211a7356ea3c29fc43450
Reset metadata.
Loaded project: soy_test
Current shape and databases in the MetaDataStore: (0, 0) set()
Adding: biosphere3
Adding: Forwast_database
Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tab.py", line 60, in generate_setup
    new_tab = LCAResultsSubTab(cs_name, presamples, self)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 120, in __init__
    self.setup_tabs()
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 181, in setup_tabs
    self._update_tabs()
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 192, in _update_tabs
    tab.update_tab()
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 567, in update_tab
    self.lca_overview_widget.update_tab()
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\ui\tabs\LCA_results_tabs.py", line 678, in update_tab
    self.df = self.parent.contributions.lca_scores_df(normalized=self.relative)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\bwutils\multilca.py", line 588, in lca_scores_df
    return self._build_lca_scores_df(scores)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\bwutils\multilca.py", line 581, in _build_lca_scores_df
    joined = joined.loc[:, col_order.append(methods)]
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 889, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1069, in _getitem_tuple
    return self._getitem_tuple_same_dim(tup)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 775, in _getitem_tuple_same_dim
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1113, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1053, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pandas\core\indexing.py", line 1322, in _validate_read_indexer
    "Passing list-likes to .loc or [] with any missing labels "
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['reference product'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```

**Comment by marc-vdm** [comment]
Additional update:
I tried making a sample database with just 2 processes to demonstrate the issue clearer. With one requiring itself as input, but it seems this is not possible in AB: When dragging the process itself to the process in the 'activity details' tab, the process is placed in the 'products' table instead of the 'technosphere inputs' table.

**Comment by marc-vdm** [comment]
Additional update 2:
When the user with this original problem tried to run the LCA in AB as I tried above, they got this (different) error:

```
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['reference product'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
```
