### ISSUE TITLE
updating AB breaks AB

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#604]
Updating AB by `conda update -n ab --channel conda-forge activity-browser` (copy pasted from instructions) broke my (non-dev) AB environment. It could be an issue with BW?

```
Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser.app import run_activity_browser
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\__init__.py", line 8, in <module>
    from .app import Application, run_activity_browser
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\__init__.py", line 7, in <module>
    from .application import Application
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\application.py", line 2, in <module>
    from .controller import Controller
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\activity_browser\app\controller.py", line 5, in <module>
    import brightway2 as bw
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\brightway2\__init__.py", line 3, in <module>
    from bw2calc import *
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\bw2calc\__init__.py", line 26, in <module>
    from .lca import LCA
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\bw2calc\lca.py", line 29, in <module>
    from pypardiso import factorized, spsolve
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\scipy_aliases.py", line 9, in <module>
  File "C:\Users\m\miniconda3\envs\ab\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\pardiso_wrapper.py", line 66, in __init__
  File "C:\Users\m\miniconda3\envs\ab\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by mixib** [comment]
Updating AB_dev by 

```
conda activate ab_dev
conda update --channel conda-forge activity-browser-dev
```
 (copy pasted from instructions) broke my dev AB environment. Same issue as [original post](https://github.com/LCA-ActivityBrowser/activity-browser/issues/604#issue-905105172?)? 
 
 ```
 (debug01) PS C:\> activity-browser
Traceback (most recent call last):
  File "C:\Users\hello\Miniconda3\envs\debug01\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\activity_browser\__init__.py", line 9, in <module>
    from .application import Application
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\activity_browser\application.py", line 2, in <module>
    from .controllers import controllers
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\activity_browser\controllers\__init__.py", line 2, in <module>
    from .activity import ActivityController, ExchangeController
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\activity_browser\controllers\activity.py", line 5, in <module>
    import brightway2 as bw
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\brightway2\__init__.py", line 3, in <module>
    from bw2calc import *
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\bw2calc\__init__.py", line 26, in <module>
    from .lca import LCA
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\bw2calc\lca.py", line 29, in <module>
    from pypardiso import factorized, spsolve
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\scipy_aliases.py", line 9, in <module>
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\site-packages\pypardiso-0.2.2-py3.6.egg\pypardiso\pardiso_wrapper.py", line 66, in __init__
  File "C:\Users\hello\Miniconda3\envs\debug01\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by StpdFox** [comment]
This seems to be an issue regarding the upgrade to python 3.8. 
I've reverted the version updates back and will do more testing on the dev branch on Github. 
These changes will take about an hour to update on conda. So we'll test it soon

**Comment by StpdFox** [comment]
Have you tried installing the release version? instead of the dev? Did you get the same result?

**Comment by StpdFox** [comment]
The issue relates to a bug in [brightway](https://github.com/brightway-lca/brightway2-calc/issues/36) They are working on it, i'm trying to chip in but it did mess up conda.

**Comment by StpdFox** [comment]
There's a workaround. You have to create a new enviroment with this command :
`conda create -n <Your Environment Name> -c conda-forge -c cmutel -c bsteubing -c haasad -c pascallesage  "activity-browser>2.4" mkl=2020.2 python=3.8`

Then activate that environment by typing 
`conda activate <Your Environment Name>`

and run the AB by typing 
`activity-browser`

i hope this works for you.
