### ISSUE TITLE
 cannot import name 'ParallelMonteCarlo' from 'bw2calc'

### ISSUE THREAD

**Issue by Bubu25** [LCA-ActivityBrowser/activity-browser#657]
Hi,

By doing a new installation of activity-browser and brightway I got the following error: 

      (C:\ProgramData\MiniforgeEnvs\ab_dev4) C:\WINDOWS\system32>activity-browser
      Traceback (most recent call last):
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\Scripts\activity-browser-script.py", line 5, in <module>
          from activity_browser import run_activity_browser
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\__init__.py", line 9, in <module>
          from .application import Application
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\application.py", line 2, in <module>
          from .controllers import controllers
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\controllers\__init__.py", line 2, in <module>
          from .activity import ActivityController, ExchangeController
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\controllers\activity.py", line 10, in <module>
          from activity_browser.bwutils import AB_metadata, commontasks as bc
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\bwutils\__init__.py", line 8, in <module>
          from .multilca import MLCA, Contributions
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\activity_browser\bwutils\multilca.py", line 7, in <module>
          from bw2analyzer import ContributionAnalysis
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\bw2analyzer\__init__.py", line 21, in <module>
          from .report import SerializedLCAReport
        File "C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\bw2analyzer\report.py", line 5, in <module>
          from bw2calc import  LCA, GraphTraversal, ParallelMonteCarlo
      ImportError: cannot import name 'ParallelMonteCarlo' from 'bw2calc' (C:\ProgramData\MiniforgeEnvs\ab_dev4\lib\site-packages\bw2calc\__init__.py)

Best regards,

**Comment by haasad** [comment]
Temorary fix you can use to make it work:
```
conda install bw2calc=1.8.0
```

**Comment by Bubu25** [comment]
Thank you.
This has fixed the issue.
