### ISSUE TITLE
AB installation not work fully working

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#666]
when I install the ab like this:
`conda create -n ab38 activity-browser python=3.8`

I get this error when trying to run the AB:

> Traceback (most recent call last):
  File "C:/Users/steub/surfdrive/Leiden/python/GitHub/LCA-ActivityBrowser/activity-browser/run-activity-browser.py", line 2, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\__init__.py", line 9, in <module>
    from .application import Application
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\application.py", line 2, in <module>
    from .controllers import controllers
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\controllers\__init__.py", line 2, in <module>
    from .activity import ActivityController, ExchangeController
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\controllers\activity.py", line 10, in <module>
    from activity_browser.bwutils import AB_metadata, commontasks as bc
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\__init__.py", line 8, in <module>
    from .multilca import MLCA, Contributions
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\bwutils\multilca.py", line 7, in <module>
    from bw2analyzer import ContributionAnalysis
  File "C:\Users\steub\miniconda3\envs\ab38\lib\site-packages\bw2analyzer\__init__.py", line 21, in <module>
    from .report import SerializedLCAReport
  File "C:\Users\steub\miniconda3\envs\ab38\lib\site-packages\bw2analyzer\report.py", line 5, in <module>
    from bw2calc import ParallelMonteCarlo, LCA, GraphTraversal
ImportError: cannot import name 'ParallelMonteCarlo' from 'bw2calc' (C:\Users\steub\miniconda3\envs\ab38\lib\site-packages\bw2calc\__init__.py)

Process finished with exit code 1

**Comment by cmutel** [comment]
@bsteubing This is occurring because conda is installing a development version of `bw2calc` (2.0.dev2), which I didn't realize would happen. `pip`, for example, only install dev packages if you explicitly ask for them.

An easy fix for now would be to pin the dependency in the AB conda package to 1.8.0.

**Comment by cmutel** [comment]
Until this is fixed in the recipe, you can force the `bw2calc` version by adding `bw2calc=1.8.0` to the conda command, e.g.

```
conda create -n ab_bw2calc_fix activity-browser bw2calc=1.8.0
```

**Comment by cmutel** [comment]
@gudivadas This appears to be a packaging problem with `SALib`. You can manually install [importlib_metdata](https://importlib-metadata.readthedocs.io/en/latest/). What version of Python did you get? `importlib_metadata` was added to the stdlib in Py 3.8.

**Comment by gudivadas** [comment]
@cmutel Thank you for your reply. It worked when I used this
`conda create -n ab_bw2calc_fix activity-browser bw2calc=1.8.0` 

Although, previously I used `conda install bw2calc=1.8.0`  and then tried to install activity browser, but it did not work and I got the previous posted error.

**Comment by bsteubing** [comment]
OK, I see Chris suggestion here too late, we have fixed it via the requirements, but this is something to keep in mind should we run into similar problems in the future. 
@nabilahmed739 FYI, if you haven't see this issue yet
