### ISSUE TITLE
Error when calculating, access violation writing 

### ISSUE THREAD

**Issue by SELTENEERDEN** [LCA-ActivityBrowser/activity-browser#694]
I have a rather urgent problem. I have to give a short introduction to the Activity Browser to a small audience of colleagues and externals on Friday and I can't get anything calculated right now. 
It all started after I updated the developer version of the AB via "conda update activity-browser-dev". But the problem also excists in the regular AB version. It all works up to the point where I actually click on Calculation. The error message I see in the CMD (and also in the debugger window) is "self._mkl_pardiso(self.pt.ctypes.data_as(ctypes.POINTER(self._pt_type[0])), # pt
OSError: exception: access violation writing 0x000000000004". 

I already tried uninstalling everything including Anaconda. I tried using different projects with different impact categories or even just a single ecoinvent activity but nothing works. My workstation is a Windows 10 System and everything used to work before.

I think it has something to do with Paradiso, but don't know for sure. @haasad  Can you maybe help me?

**Comment by marc-vdm** [comment]
I just tried and re-installed the dev environment and -unfortunately- I can replicate the issue. Here's the full error:

```
Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 60, in generate_setup
    new_tab = LCAResultsSubTab(cs_name, presamples, self)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 101, in __init__
    self.do_calculations()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 128, in do_calculations
    self.mlca = MLCA(self.cs_name)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\multilca.py", line 124, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 342, in lci
    self.lci_calculation()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 350, in lci_calculation
    self.supply_array = self.solve_linear_system()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 314, in solve_linear_system
    return self.solver(self.demand_array)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\scipy_aliases.py", line 46, in spsolve
    solver.factorize(A)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 150, in factorize
    self._call_pardiso(A, b)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 281, in _call_pardiso
    raise PyPardisoError(pardiso_error.value)
pypardiso.pardiso_wrapper.PyPardisoError: The Pardiso solver failed with error code -3. See Pardiso documentation for details.

Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 60, in generate_setup
    new_tab = LCAResultsSubTab(cs_name, presamples, self)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 101, in __init__
    self.do_calculations()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 128, in do_calculations
    self.mlca = MLCA(self.cs_name)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\multilca.py", line 124, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 342, in lci
    self.lci_calculation()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 350, in lci_calculation
    self.supply_array = self.solve_linear_system()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 314, in solve_linear_system
    return self.solver(self.demand_array)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\scipy_aliases.py", line 48, in spsolve
    x = solver.solve(A, b)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 174, in solve
    x = self._call_pardiso(A, b)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 263, in _call_pardiso
    self._mkl_pardiso(self.pt.ctypes.data_as(ctypes.POINTER(self._pt_type[0])),  # pt
OSError: exception: access violation writing 0x0000000000000004
```

**Comment by marc-vdm** [comment]
Update, I'm unable to replicate the error on Linux, perhaps that information may help in resolving the issue

@SELTENEERDEN While your issue should for sure be fixed, if we don't manage in time, though for sure not ideal, perhaps using linux could at least allow you to use AB for coming Fri?

**Comment by haasad** [comment]
I also can't replicate it on linux. I don't have access to a windows machine on short notice to run some tests, could you please run the below code in your problematic environment to check if something is fundamentally broken with pypardiso?
```
import pypardiso
import numpy as np
import scipy.sparse as sp
A = sp.rand(100, 100, density=0.5, format='csr')
b = np.random.rand(100)
x = pypardiso.spsolve(A, b)
```
If yes, as a next step I'd try to downgrade mkl itself:
```
conda install mkl=2021.3
```
There have been problems in the past with new releases of mkl (eg. https://github.com/haasad/PyPardisoProject/issues/12)

**Comment by marc-vdm** [comment]
I tried to run the code and got no errors. Also, I tried downgrading mkl to `2021.3`, giving me the below error on calculation, which looks to me like the top half of the error I got yesterday:

```
Traceback (most recent call last):
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 60, in generate_setup
    new_tab = LCAResultsSubTab(cs_name, presamples, self)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 101, in __init__
    self.do_calculations()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 128, in do_calculations
    self.mlca = MLCA(self.cs_name)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\multilca.py", line 124, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 342, in lci
    self.lci_calculation()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 350, in lci_calculation
    self.supply_array = self.solve_linear_system()
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\bw2calc\lca.py", line 314, in solve_linear_system
    return self.solver(self.demand_array)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\scipy_aliases.py", line 46, in spsolve
    solver.factorize(A)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 150, in factorize
    self._call_pardiso(A, b)
  File "C:\Users\m\miniconda3\envs\ab_dev\lib\site-packages\pypardiso\pardiso_wrapper.py", line 281, in _call_pardiso
    raise PyPardisoError(pardiso_error.value)
pypardiso.pardiso_wrapper.PyPardisoError: The Pardiso solver failed with error code -3. See Pardiso documentation for details.
```

**Comment by SELTENEERDEN** [comment]
Thank you all for getting back to me so soon. Unfortunately by now I could not fix the issue. The mkl 2021.3 is also giving me errors.
I have an old version on another machine which I will propably use for the presentation of the software, if we do not find a solution today.

**Comment by haasad** [comment]
Ugly workaround that should give you a usable environment:
```
conda create -n abfixed activity-browser-dev
conda activate abfixed
conda remove pypardiso numpy scipy mkl --force
pip install pypardiso
```
Please let me know if that works for you.

**Comment by SELTENEERDEN** [comment]
> Ugly workaround that should give you a usable environment:
> 
> ```
> conda create -n abfixed activity-browser-dev
> conda activate abfixed
> conda remove pypardiso numpy scipy mkl --force
> pip install pypardiso
> ```
> 
> Please let me know if that works for you.

@haasad That does the trick. Thank you so much!

**Comment by Haniezarafshani** [comment]
Hello,

I had the same problem and this trick solved my problem, but today when I started to work with AB, again the calculate does not work:(
I again repeat this solution but apparently, it does not work anymore.
I searches and try deleting (ibiomp5md.dll!), but it does not work too
Thank you very much for your help

**Comment by haasad** [comment]
Hi @Haniezarafshani,

can you try creating an new environment with the commands below and check if that works?
```
conda create -n ab_fixed activity-browser intel-openmp=2021.4
conda activate ab_fixed
activity-browser
```

If it doesn't, please provide some information on what error exactly you experience.

**Comment by Haniezarafshani** [comment]
> Hi @Haniezarafshani,
> 
> can you try creating an new environment with the commands below and check if that works?
> 
> ```
> conda create -n ab_fixed activity-browser-dev intel-openmp=2021.4
> conda activate ab_fixed
> activity-browser
> ```
> 
> If it doesn't, please provide some information on what error exactly you experience.

Thank you very much! you saved my life:)

**Comment by bsteubing** [comment]
Hi @haasad, thanks for all of your support here. I have not really looked into this, but is "intel-openmp=2021.4" a dependency/requirement that we should add to the AB or is this just an edge case?

**Comment by haasad** [comment]
Hi @bsteubing, please see me summary here: https://github.com/haasad/PyPardisoProject/issues/36#issuecomment-1010993849

**Comment by haasad** [comment]
Fixed upstream, see https://github.com/haasad/PyPardisoProject/issues/36 for details

**Comment by SELTENEERDEN** [comment]
Again, I have a problem when hitting the calculate button. Even in the ab_fixed environment. The Debug-Window shows the following:

Traceback (most recent call last):
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 56, in generate_setup
    new_tab = LCAResultsSubTab(data, self)
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 103, in __init__
    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\calculations.py", line 17, in do_LCA_calculations
    mlca = MLCA(cs_name)
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\multilca.py", line 123, in __init__
    self.lca = self._construct_lca()
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\multilca.py", line 166, in _construct_lca
    return bw.LCA(demand=self.func_units_dict, method=self.methods[0])
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2calc\lca.py", line 79, in __init__
    clean_databases()
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2calc\utils.py", line 102, in clean_databases
    databases.clean()
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\meta.py", line 121, in clean
    return _clean()
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\project.py", line 358, in writable_project
    return wrapped(*args, **kwargs)
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\meta.py", line 114, in _clean
    Database(x).process()
  File "C:\Users\benjamin.fritz\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\backends\peewee\database.py", line 445, in process
    if np.isnan(data['amount']) or np.isinf(data['amount']):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by haasad** [comment]
@SELTENEERDEN would you mind opening a new issue for this? At first glance this does not look related to this original issue at all to me.
