### ISSUE TITLE
database import error when no calculation setups exist [problem with signals?]

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#699]
Using AB version `2.6.7`.

AB gives an error (below) when the database import (through 7zip) is finished (before pressing the `Finish` button) regarding the name of a calculation setup when no setups have been made yet. This is probably an edge case caused by a signal that doesn't currently check for the case when no calculation setups exist.
This error does not affect the actual database import or resulting database.

```
Created database: ei36
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ab\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py", line 40, in sync
    raise ValueError("'name' cannot be None if no name is set")
ValueError: 'name' cannot be None if no name is set
```

The error duplicates when there are multiple databases (besides `biosphere 3`) have been imported. Below is the error for the second import in the same session. We probably need to check for a signal that is emitted for each of the databases?

```
Created database: ei38
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ab\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py", line 40, in sync
    raise ValueError("'name' cannot be None if no name is set")
ValueError: 'name' cannot be None if no name is set

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\ab\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py", line 40, in sync
    raise ValueError("'name' cannot be None if no name is set")
ValueError: 'name' cannot be None if no name is set
```

**Comment by marc-vdm** [comment]
probably easiest time-wise to fix together with #623
