### ISSUE TITLE
Validation Error in Sensitivity Analysis 

### ISSUE THREAD

**Issue by nabilahmed739** [LCA-ActivityBrowser/activity-browser#740]
Environment: Windows 10, Python 3.8

![image](https://user-images.githubusercontent.com/6296604/155634587-171183e1-ae79-4ff2-9cb9-bac01d5f18a2.png)

**Stacktrace:**
> -- GSA --
>  Project: ... Activity: '...' (unit, VN, None) Method: ('IPCC 2013', 'climate change', 'GWP 100a')
> Non-stochastic LCA score: 0.8826030059990888
> TECHNOSPHERE (19608, 19608) filtering resulted in 384 of 241263 exchanges and took 2071 iterations in 23.0 seconds.
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\ab_master38\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 1375, in calculate_gsa
>     self.GSA.perform_GSA(act_number=act_number, method_number=method_number,
>   File "C:\ProgramData\Anaconda3\envs\ab_master38\lib\site-packages\activity_browser\bwutils\sensitivity_analysis.py", line 320, in perform_GSA
>     self.t_exchanges, self.t_indices = get_exchanges(self.lca, self.t_indices)
>   File "C:\ProgramData\Anaconda3\envs\ab_master38\lib\site-packages\activity_browser\bwutils\sensitivity_analysis.py", line 113, in get_exchanges
>     exchanges, indices = drop_no_uncertainty_exchanges(exchanges, indices)
>   File "C:\ProgramData\Anaconda3\envs\ab_master38\lib\site-packages\activity_browser\bwutils\sensitivity_analysis.py", line 122, in drop_no_uncertainty_exchanges
>     if exc.get('uncertainty type') >= 1:
> TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by marc-vdm** [comment]
Is this a duplicate of #690?

A fix was commented there but not committed to AB.

**Comment by nabilahmed739** [comment]
@marc-vdm Oh didnt find it earlier, will mark it as a duplicate. 
I have already fixed this but it needs confirmation(by someone who understands how to interpret GSA), I will create a PR soon.
I know about the paper for GSA, I have limited time at hand else I could verify it later.

**Comment by marc-vdm** [comment]
Nice that you already managed to fix it.
Best to tag @bsteubing as reviewer, I also don't know much about GSA its implementation.

**Comment by ar-ali** [comment]
Hi,
Can you please suggest how to solve this issue?

**Comment by nabilahmed739** [comment]
@ar-ali The issue is under review, if you are running AB from code then you can run this branch for the fix: bugfix-740 OR wait for the PR #766 to be completed and merged.
