### ISSUE TITLE
Database import failed from ecoinvent website

### ISSUE THREAD

**Issue by mmyridinas** [LCA-ActivityBrowser/activity-browser#750]
I am trying to import the 3.8 cut off version of the ecoinvent database but as soon as I start the importing process I get an error message:

```
Database import interrupted!
database already downloaded
Traceback (most recent call last):
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 704, in run
    self.run_ecoinvent()
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 717, in run_ecoinvent
    self.run_extract(temp_dir)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 756, in run_extract
    self.downloader.extract(target_dir=temp_dir)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 1218, in extract
    self.extraction_process = subprocess.Popen(extract_cmd, stdout=subprocess.DEVNULL)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```
So this is the error message.
The AB version I am using is 2.6.8.

The conda list output is:

```
# Name                    Version                   Build  Channel
activity-browser          2.6.8                      py_0    bsteubing
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brightway2                2.4.1                      py_1    cmutel
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotli-python             1.0.9            py39h415ef7b_6    conda-forge
brotlicffi                1.0.9.2          py39h415ef7b_1    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1003    conda-forge
bw2analyzer               0.10                       py_1    cmutel
bw2calc                   1.8.0                      py_0    cmutel
bw2data                   3.6.4                      py_0    cmutel
bw2io                     0.8.6                      py_1    cmutel
bw2parameters             0.7                        py_0    cmutel
bw_migrations             0.1                        py_0    cmutel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_1    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.1           py39h7bc7c5c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      1.4.2                      py_0    haasad
eight                     1.0.0                      py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.30.0           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py39hcbf5309_4    conda-forge
fuzzywuzzy                0.18.0             pyhd8ed1ab_0    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hcbf5309_0    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
kiwisolver                1.3.2            py39h2e07f2f_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              13_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              13_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              13_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lxml                      4.8.0            py39h4fd7cdf_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-base           3.5.1            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mrio_common_metadata      0.1.1                      py_0    cmutel
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.12.2        py39hb82d6ee_1    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
numpy                     1.22.3           py39h6331f09_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h2e25243_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
peewee                    3.14.10          py39h539719c_0    conda-forge
pillow                    9.0.1            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
presamples                0.2.5                h39e3cac_0    pascallesage
psutil                    5.9.0            py39hb82d6ee_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.18.1             pyhd8ed1ab_0    conda-forge
pybcj                     0.5.0            py39hb82d6ee_2    conda-forge
pybcpy                    0.0.17             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.14.1           py39hb82d6ee_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyppmd                    0.18.0           py39h415ef7b_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1002    conda-forge
pyside2                   5.13.2           py39hc084194_4    conda-forge
pysocks                   1.7.1            py39hcbf5309_4    conda-forge
python                    3.9.10          h9a09f29_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-levenshtein        0.12.2           py39hb82d6ee_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.1           py39h46500c5_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
salib                     1.4.5              pyh6c4a22f_0    conda-forge
scipy                     1.7.3            py39hc0c34ad_0    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                60.9.3           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
stats_arrays              0.6.5                      py_2    cmutel
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_0    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
voluptuous                0.12.2             pyhd8ed1ab_1    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_5    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_3    conda-forge
wrapt                     1.14.0           py39hb82d6ee_0    conda-forge
xlrd                      1.2.0              pyh9f0ad1d_1    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipfile-deflate64         0.2.0            py39hb82d6ee_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
```

Thank you very much in advance for your time
Have a nice day

**Comment by mmyridinas** [comment]
FYI, In addition to my post, I also tried to import the database through local import of an 7z file but I received the same error message"

```
DevTools listening on ws://127.0.0.1:3999/devtools/browser/25777708-d0dc-4cc7-968a-ed20f30345bf
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\Lenovo\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loading user settings:
dirpath already loaded
Brightway2 data directory: C:\Users\Lenovo\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Traceback (most recent call last):
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 702, in run
    self.run_extract_import()
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 770, in run_extract_import
    self.run_extract(tempdir)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 756, in run_extract
    self.downloader.extract(target_dir=temp_dir)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\site-packages\activity_browser\ui\wizards\db_import_wizard.py", line 1218, in extract
    self.extraction_process = subprocess.Popen(extract_cmd, stdout=subprocess.DEVNULL)
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Lenovo\miniconda3\envs\ab\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

So I still am not able to import the database.

**Comment by haasad** [comment]
@mmyridinas Please check my answer in https://github.com/LCA-ActivityBrowser/activity-browser/issues/742#issuecomment-1060466627

@bsteubing Can you look into releasing an new stable version? There are some bug fixes already merged in master that could prevent some frustration for people using the stable version. There's also a PR open that automates most steps of releasing the stable version (#733), so it should be less work than it used to be.

**Comment by mmyridinas** [comment]
Thank you @haasad

**Comment by haasad** [comment]
I assume my linked comment solved your problem, please reopen if that's not the case

**Comment by marc-vdm** [comment]
@haasad BS will be out of office for some time.

I'd be happy to create a release, but I'm still learning this side of GH. 
Do you know if I can create a release tag and not include https://github.com/LCA-ActivityBrowser/activity-browser/commit/80a5680505ebb975ec78c5db6ccbf833b9a299e6 and https://github.com/LCA-ActivityBrowser/activity-browser/commit/89f66ac6026fdbab60e7fe9203ce4726bd202606? Ideally, those would not be included as they still both need some work. If this is not possible, I could prioritize finishing the work in those branches.
