### ISSUE TITLE
AssertionError: Cannot find all keys.

### ISSUE THREAD

**Issue by simb-sdu** [LCA-ActivityBrowser/activity-browser#755]
I still get the key error when calculating scenario lca

I changed the max_rows value in line 472 of Anaconda3\envs\PREMISE\Lib\site-packages\pandas\io\formats\excel.py. don't know if this causes the error? I had increase the max allowed number of rows in order to make the superstructure database with PREMISE and ecoinvent 3.8 cutoff

```
Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 257, in scenario_calculation
    'data': self.scenario_panel.combined_dataframe(),
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 424, in combined_dataframe
    manager = SuperstructureManager(*data)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 21, in __init__
    SuperstructureManager.remove_duplicates(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 109, in remove_duplicates
    df.index = SuperstructureManager.build_index(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 126, in build_index
    assert df.loc[:, EXCHANGE_KEYS].notna().all().all(), "Cannot find all keys."
AssertionError: Cannot find all keys.
```
_Originally posted by @simb-sdu in https://github.com/LCA-ActivityBrowser/activity-browser/issues/432#issuecomment-1074218363_

**Comment by marc-vdm** [comment]
Could you post the `conda list` output (type that in the terminal and copy paste the output)? The issue you mentioned is rather old, so this should not be happening with current versions of AB

It would also help if you could share the database/databases and scenario files and what calculation setup you are using so we can try to replicate the problem.

**Comment by simb-sdu** [comment]
> It would also help if you could share the database/databases and scenario files and what calculation setup you are using so we can try to replicate the problem.

superstructure database is created based on the IMAGE SSP2-Base default scenarios supplied with PREMISE. I am not sure if I can share these files publicly, as I had to request en encryption key form the developers to unlock the default scenarios (but I guess its okay if I email you the superstructure database excel file in case this helps the troubleshooting?)

a very simple calculation setup, which works if I export the transformed databases directly into AB instead of using the superstructure database
![image](https://user-images.githubusercontent.com/94962841/159354978-ca6bd117-cb4b-46cd-a0a3-8f443a006959.png)

**Comment by simb-sdu** [comment]
Currently in the proces of trying everything with ecoinvent 3.7.1 and 3.6 to see if that makes any difference.

**Comment by marc-vdm** [comment]
Thanks for the info!

>superstructure database is created based on the IMAGE SSP2-Base default scenarios supplied with PREMISE. I am not sure if I can share these files publicly, as I had to request en encryption key form the developers to unlock the default scenarios (but I guess its okay if I email you the superstructure database excel file in case this helps the troubleshooting?)

No worries, I should have that DB somewhere as well.

I see in the screenshot that you've used  `washing machince`  from the `ecoinvent 3.8 cutoff` database. Are you sure that is the right database in combination with those scenarios? In your database list on the left there are also some `Remind` databases, it could be you're required to use those instead. 

If that is indeed the problem, you may also want to include all of the premise scenarios in one [super structure database](https://link.springer.com/article/10.1007/s11367-021-01974-2) to assess using different years in the same scenario (e.g. SSP2 base). For that, I'd recommend having a look at the [premsie docs](https://premise.readthedocs.io/en/latest/), as I don't know from the top of my head how to do that.

Hope that helps!

**Comment by marc-vdm** [comment]
@simb-sdu If your problem is resolved, please let us know so we can close the issue.

**Comment by marc-vdm** [comment]
> 2. created a new superstructure database for ecoinvent 3.8 cutoff. I am able to load the superstructure scenario file, but when calculating, i get the "AssertionError: Cannot find all keys"

Did you also update the reference flow to come from that new database?
> 3. i tried taking the `washing machine` reference flow from the `Remind` databses - it made no difference, and in theory it should not make any difference. tried other reference flows as well, no difference

Could you perhaps edit the scenario file to only contain a few (~10ish) edited flows and see if it is still broken? Sharing such a file should not be a licensing problem as the information contained is very limited. But sharing that would help me troubleshoot.

**Comment by simb-sdu** [comment]
Superstructure database from `update_steel()` ie. only steel sector from `Remind` is transformed. With this database, there is no errors, and it works perfectly. See output below

```

(base) C:\Users\simb>conda activate ab_dev

(ab_dev) C:\Users\simb>activity-browser
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/1e158180-a3a6-454e-b188-4f658de0ebd5
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\simb\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loading user settings:
dirpath already loaded
Reset project settings directory to: C:\Users\simb\AppData\Local\pylca\Brightway3\premise5.229fb8035d480137d0111334f1b0618c
Loaded project: premise5
Brightway2 data directory: C:\Users\simb\AppData\Local\pylca\Brightway3
Brightway2 active project: premise5
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
2022-03-25T10:49:08.020ZE [7404:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:49:08.023ZE [7404:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
2022-03-25T10:49:08.024ZE [26284:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:49:08.024ZE [26284:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
2022-03-25T10:49:08.024ZE [25708:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:49:08.025ZE [25708:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
Loading Scenario file. This may take a while for large files
Current shape and databases in the MetaDataStore: (0, 0) set()
Adding: biosphere3
Adding: super_db_2022-03-25
+showing tab: LCA results
Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\backends\backend_qt.py", line 347, in resizeEvent
    self.figure.set_size_inches(winch, hinch, forward=False)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\figure.py", line 2662, in set_size_inches
    raise ValueError(f'figure size must be positive finite not {size}')
ValueError: figure size must be positive finite not [ 0.4  -0.09]

Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\backends\backend_qt.py", line 347, in resizeEvent
    self.figure.set_size_inches(winch, hinch, forward=False)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\figure.py", line 2662, in set_size_inches
    raise ValueError(f'figure size must be positive finite not {size}')
ValueError: figure size must be positive finite not [ 0.4  -0.09]

Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\backends\backend_qt.py", line 347, in resizeEvent
    self.figure.set_size_inches(winch, hinch, forward=False)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\figure.py", line 2662, in set_size_inches
    raise ValueError(f'figure size must be positive finite not {size}')
ValueError: figure size must be positive finite not [ 0.34 -0.09]

Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\backends\backend_qt.py", line 347, in resizeEvent
    self.figure.set_size_inches(winch, hinch, forward=False)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\matplotlib\figure.py", line 2662, in set_size_inches
    raise ValueError(f'figure size must be positive finite not {size}')
ValueError: figure size must be positive finite not [ 0.34 -0.09]

Current shape and databases in the MetaDataStore: (25280, 30) {'biosphere3', 'super_db_2022-03-25'}
```


**But the superstructure database with `update_all()` ie. where all sectors from `Remind` are transformed, gives the `assertion error: key not found` see output below.**


```
Adding: super_db_2022-03-24
Pandas Dataframe passed to sync. (0, 5)
Pandas Dataframe passed to sync. (149, 5)
Pandas Dataframe passed to sync. (0, 5)
Pandas Dataframe passed to sync. (0, 5)
Pandas Dataframe passed to sync. (0, 5)
Pandas Dataframe passed to sync. (3, 5)
Dropevent from: <activity_browser.ui.tables.inventory.ActivitiesBiosphereTable(0x2133bbbeae0) at 0x000002133708F640>
C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py:151: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._dataframe = self._dataframe.append(data, ignore_index=True)
2022-03-25T10:51:26.266ZE [7404:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:51:26.266ZE [7404:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
2022-03-25T10:51:26.269ZE [26284:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:51:26.271ZE [26284:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
2022-03-25T10:51:26.273ZE [25708:ShellIpcClient] shell_ipc_client.cc:129:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_simb_shell
2022-03-25T10:51:26.274ZE [25708:ShellIpcClient] shell_ipc_client.cc:602:operator() Failed to connect to the server: Status::UNAVAILABLE_RESOURCE
Loading Scenario file. This may take a while for large files
Traceback (most recent call last):
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 257, in scenario_calculation
    'data': self.scenario_panel.combined_dataframe(),
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 424, in combined_dataframe
    manager = SuperstructureManager(*data)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 21, in __init__
    SuperstructureManager.remove_duplicates(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 109, in remove_duplicates
    df.index = SuperstructureManager.build_index(df)
  File "C:\Users\simb\Anaconda3\envs\ab_dev\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 126, in build_index
    assert df.loc[:, EXCHANGE_KEYS].notna().all().all(), "Cannot find all keys."
AssertionError: Cannot find all keys.
```


I will try to make a superstructure database for all sectors individually (like i did for the steel) tp test them individually to try and lcoate the error.

**Comment by simb-sdu** [comment]
> > 2. created a new superstructure database for ecoinvent 3.8 cutoff. I am able to load the superstructure scenario file, but when calculating, i get the "AssertionError: Cannot find all keys"
> 
> Did you also update the reference flow to come from that new database?
> 
> > 3. i tried taking the `washing machine` reference flow from the `Remind` databses - it made no difference, and in theory it should not make any difference. tried other reference flows as well, no difference
> 
> Could you perhaps edit the scenario file to only contain a few (~10ish) edited flows and see if it is still broken? Sharing such a file should not be a licensing problem as the information contained is very limited. But sharing that would help me troubleshoot.



> > 2. created a new superstructure database for ecoinvent 3.8 cutoff. I am able to load the superstructure scenario file, but when calculating, i get the "AssertionError: Cannot find all keys"
> 
> Did you also update the reference flow to come from that new database?
Yes. Although this is necessary in order to sue the sueprstructure, it does not resolve the missing keys issue


> 
> Could you perhaps edit the scenario file to only contain a few (~10ish) edited flows and see if it is still broken? Sharing such a file should not be a licensing problem as the information contained is very limited. But sharing that would help me troubleshoot.

Thanks. I am not sure this will elicit the issue, if we consider my comment above. I will experiment more next week and get back!

**Comment by marc-vdm** [comment]
Sorry, I really can't do something about the issue if I don't have all of the following:

1. Database
2. Scenario file
3. Reference flow you're using

With those datapoints I can actually see what is happening and try to replicate the problem, this terminal output is not helping me further at the moment. Unfortunately I can't really prove I an ecoinvent license, so that it would be 'safe' to share this, but I'm guessing you'll need to trust me 👍. If you could share your files with me [here](https://leidenuniv1-my.sharepoint.com/:f:/g/personal/meidemtvander_vuw_leidenuniv_nl/EhWAtYgCuMJJqt2bsQwzpZcBbRsofS1Ycq6AAH_0WprRDg), it at least doesn't end up on the public internet.

Otherwise, I'm not sure how I could help you further.

**Comment by simb-sdu** [comment]
problem was related to the genration of the sueprstructure database in PREMISE.  #https://github.com/polca/premise/issues/65
