### ISSUE TITLE
Error when calculating, truth value in array is ambigiuous

### ISSUE THREAD

**Issue by SELTENEERDEN** [LCA-ActivityBrowser/activity-browser#780]
The problem excists in the regular AB version and in the developer. It all works up to the point where I actually click on Calculation. I already reinstalled Anaconda without success. I am on a Windows 10 64-bit machine with Anaconda Navigator 2.1.1.

The debug window in the AB shows:
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 56, in generate_setup
    new_tab = LCAResultsSubTab(data, self)
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 103, in __init__
    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\calculations.py", line 17, in do_LCA_calculations
    mlca = MLCA(cs_name)
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\multilca.py", line 123, in __init__
    self.lca = self._construct_lca()
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\activity_browser\bwutils\multilca.py", line 166, in _construct_lca
    return bw.LCA(demand=self.func_units_dict, method=self.methods[0])
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2calc\lca.py", line 79, in __init__
    clean_databases()
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2calc\utils.py", line 102, in clean_databases
    databases.clean()
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\meta.py", line 121, in clean
    return _clean()
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\project.py", line 358, in writable_project
    return wrapped(*args, **kwargs)
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\meta.py", line 114, in _clean
    Database(x).process()
  File "C:\Users\user\Anaconda3\envs\ab_fixed\lib\site-packages\bw2data\backends\peewee\database.py", line 445, in process
    if np.isnan(data['amount']) or np.isinf(data['amount']):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

This is my conda list output:

# Name                    Version                   Build  Channel
activity-browser-dev      2022.04.29                 py_0    bsteubing
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asteval                   0.9.26             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
brightway2                2.4.2                      py_4    cmutel
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotli-python             1.0.9            py39h415ef7b_7    conda-forge
brotlicffi                1.0.9.2          py39h415ef7b_2    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
bw2analyzer               0.10                       py_1    cmutel
bw2calc                   1.8.1                      py_2    cmutel
bw2data                   3.6.4                      py_0    cmutel
bw2io                     0.8.6                      py_1    cmutel
bw2parameters             0.7                        py_0    cmutel
bw_migrations             0.1                        py_0    cmutel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2021.10.8        py39hcbf5309_2    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h7bc7c5c_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      1.5.1                      py_0    bsteubing
eight                     1.0.0                      py_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.33.3           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py39hcbf5309_5    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py39hcbf5309_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
intel-openmp              2021.4.0          haa95532_3556
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_1    conda-forge
kiwisolver                1.4.2            py39h2e07f2f_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libblas                   3.9.0              14_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              14_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              14_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_0    conda-forge
libxslt                   1.1.33               h34f844d_4    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
lxml                      4.8.0            py39hb82d6ee_3    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib-base           3.5.1            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
mrio_common_metadata      0.2.1                      py_0    cmutel
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.12.2        py39hb82d6ee_2    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  2.8                pyhd8ed1ab_0    conda-forge
numpy                     1.22.3           py39h0948cea_2    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1n               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py39h2e25243_1    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
peewee                    3.14.10          py39h539719c_1    conda-forge
pillow                    9.1.0            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py39hb82d6ee_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py7zr                     0.18.5             pyhd8ed1ab_0    conda-forge
pybcj                     0.5.2            py39hb82d6ee_0    conda-forge
pybcpy                    0.0.17             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.14.1           py39hb82d6ee_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.1              pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyppmd                    0.18.2           py39h415ef7b_0    conda-forge
pyprind                   2.11.2          py39hcbf5309_1002    conda-forge
pyside2                   5.13.2           py39hc084194_8    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.12          h9a09f29_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.9              pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.1           py39h46500c5_1    conda-forge
qt                        5.12.9               h556501e_6    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
salib                     1.4.5              pyh6c4a22f_0    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
setuptools                62.1.0           py39hcbf5309_0    conda-forge
setuptools-scm            6.4.2              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.3               h8ffe710_0    conda-forge
stats_arrays              0.6.5                      py_2    cmutel
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
tabulate                  0.8.9              pyhd8ed1ab_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
texttable                 1.6.4              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.2.0              pyha770c72_1    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4            py39hcbf5309_5    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
wrapt                     1.14.1           py39hb82d6ee_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.3              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zipfile-deflate64         0.2.0            py39hb82d6ee_2    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge

**Comment by haasad** [comment]
Thanks for opening the issue. Some quick observations from my side:
- I can't reproduce the error with a fresh installation of `activity-browser-dev`
- Error message indicates that something is wrong/corrupted with one of the databases in your project

Could you maybe create a new project, add one of the ecoinvent databases and preform an LCA (any activity/method)? Like this we can rule out that something is fundamentally broken with the AB

**Comment by SELTENEERDEN** [comment]
Sorry for not getting back earlier. So i uninstalled EVERYTHING on my windows 10 machine that is in anyway related to ab, bw2, python or anaconda. Then I reinstalled Anaconda, BW2 and the AB. Of course I also had to create the biosphere flows  as well as import ecoinvent (remote) again as everything was from scratch. Unfortunately the problem is still there. Or at least I think it is the same problem because now the activity-browser crashes when I hit calculate instead of freezing and therefore I can not see the debug windows anymore. In my cmd windows it gives me the following Error:

(ab) C:\Users\user>activity-browser
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/e6f6ef01-d4d0-4b98-b670-abaf8891f188
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\benjamin.fritz\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loading user settings:
dirpath already loaded
Brightway2 data directory: C:\Users\benjamin.fritz\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version: 5.12.9
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Current shape and databases in the MetaDataStore: (0, 0) set()
Adding: cutoff38
Adding: biosphere3
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.


It looks like the last bit already provides a possible solution with this KMP_DUPLICATE_LIB_OK=TRUE, but I am really no expert and do not really know whether this is a good solution.

**Comment by haasad** [comment]
Someone else reported the same issue yesterday: https://github.com/LCA-ActivityBrowser/activity-browser/issues/783#issuecomment-1121182019

Deleting `libiomp5md.dll` fixed it in that case.

**Comment by SELTENEERDEN** [comment]
Thank you haasad. Deleting the libiomp5md.dll and -.pdb  in the folder Anaconda3\pkgs\intel-openmp-2021.4.0-haa95532_3556\Library\bin worked for me. So probably that error was not at all related to the error original error described in this issue #780. 

Regarding the original error #780 I can say, that completly uninstalling Anaconda (https://docs.anaconda.com/anaconda/install/uninstall/), deleting every trace in any file path that was related to bw2 or ab and reinstalling solved this issue.

**Comment by SELTENEERDEN** [comment]
Hello, this problem just appeared again. I can not export my databases as well. When I click on "finish" in the export windows nothing happens. I would like to reinstall bw and ab. Will I loose my projects (databases), if I do not export them? Any other way to backup them? Can I just copy&paste files from a directory on my windows machine? If so, where is this folder?

Here is the error message by the way:

```
(base) C:\Windows\system32>activate ab

(ab) C:\Windows\system32>activity-browser
-hiding tab:History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/9b99b1e6-fbb5-408d-bbe0-293d39788e38
-hiding tab:Activity Details
-hiding tab:Characterization Factors
-hiding tab:Graph Explorer
-hiding tab:LCA results
The Activity Browser log file can be found at C:\Users\benif\AppData\Local\ActivityBrowser\ActivityBrowser\Logs\ab_logs-2024-4-3_12-46-17.log
Activity Browser version: 2.9.7
Loading user settings:
dirpath already loaded
Reset project settings directory to:C:\Users\benif\AppData\Local\pylca\Brightway3\test.098f6bcd4621d373cade4e832627b4f6
Loaded project:test
Brightway2 data directory: C:\Users\benif\AppData\Local\pylca\Brightway3
Brightway2 active project: test
Qt Version:5.15.8
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\ab\Lib\site-packages\activity_browser\ui\wizards\db_export_wizard.py", line 38, in accept
    self.perform_export()
  File "C:\ProgramData\miniconda3\envs\ab\Lib\site-packages\activity_browser\ui\wizards\db_export_wizard.py", line 52, in perform_export
    EXPORTERS[export_as](db_name, out_path)
  File "C:\ProgramData\miniconda3\envs\ab\Lib\site-packages\activity_browser\bwutils\exporters.py", line 132, in store_database_as_package
    db.process()
  File "C:\ProgramData\miniconda3\envs\ab\Lib\site-packages\bw2data\backends\peewee\database.py", line 445, in process
    if np.isnan(data['amount']) or np.isinf(data['amount']):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()>
```
The environment data is
```
# packages in environment at C:\ProgramData\miniconda3\envs\ab:
#
# Name                    Version                   Build  Channel
activity-browser          2.9.7              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
asteval                   0.9.31             pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
brightway2                2.4.4              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py311h12c1d0e_1    conda-forge
brotlicffi                1.1.0.0         py311h12c1d0e_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2           py311h1ea47a8_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.10             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                hcfcfb64_5    conda-forge
ca-certificates           2024.2.2             h56e8100_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311ha68e1ae_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py311h005e61a_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
eidl                      2.0.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flask                     3.0.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.47.2          py311ha68e1ae_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.3               h12be248_0    conda-forge
glib-tools                2.78.3               h12be248_0    conda-forge
gst-plugins-base          1.22.8               h001b923_1    conda-forge
gstreamer                 1.22.8               hb4038d2_1    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
inflate64                 1.0.0           py311ha68e1ae_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50497    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.5           py311h005e61a_1    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              20_win64_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0              20_win64_mkl    conda-forge
libclang                  15.0.7          default_h77d9078_3    conda-forge
libclang13                15.0.7          default_h77d9078_3    conda-forge
libdeflate                1.19                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.3               h16e383f_0    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblapack                 3.9.0              20_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.44.2               hcfcfb64_0    conda-forge
libtiff                   4.6.0                h6e2ebb7_2    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxcb                    1.15                 hcd874cb_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lxml                      4.9.2           py311h5942461_0    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.3           py311ha68e1ae_1    conda-forge
matplotlib-base           3.8.2           py311h6e989c2_0    conda-forge
mkl                       2023.2.0         h6a75c08_50497    conda-forge
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multiprocess              0.70.15         py311ha68e1ae_1    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numpy                     1.23.5          py311h95d790f_0    conda-forge
openjpeg                  2.5.0                h3d672ee_3    conda-forge
openpyxl                  3.1.2           py311ha68e1ae_1    conda-forge
openssl                   3.2.1                hcfcfb64_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.4           py311hf63dbb6_0    conda-forge
pathos                    0.3.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h17e33f8_0    conda-forge
peewee                    3.17.0          py311had142b2_0    conda-forge
pillow                    10.2.0          py311h4dd8a23_0    conda-forge
pint                      0.21               pyhd8ed1ab_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pox                       0.3.3              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.7            pyhd8ed1ab_0    conda-forge
psutil                    5.9.7           py311ha68e1ae_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py7zr                     0.20.8             pyhd8ed1ab_1    conda-forge
pybcj                     1.0.2           py311ha68e1ae_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.19.0          py311ha68e1ae_1    conda-forge
pypardiso                 0.4.3              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pyppmd                    1.1.0           py311h12c1d0e_0    conda-forge
pyprind                   2.11.2          py311h1ea47a8_1005    conda-forge
pyside2                   5.15.8          py311h2411a93_2    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.11.0          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyzstd                    0.15.9          py311he5d195f_1    conda-forge
qt-main                   5.15.8              h9e85ed6_18    conda-forge
qt-webengine              5.15.8               h4bf5c4e_4    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
salib                     1.4.7              pyhd8ed1ab_0    conda-forge
scipy                     1.11.4          py311h0b4df5a_0    conda-forge
seaborn                   0.13.1               hd8ed1ab_0    conda-forge
seaborn-base              0.13.1             pyhd8ed1ab_0    conda-forge
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.0.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stats_arrays              0.6.6              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.1          py311h59ca53f_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
types-python-dateutil     2.8.19.20240106    pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
voluptuous                0.14.1             pyhd8ed1ab_0    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
werkzeug                  3.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py311h1ea47a8_8    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.16.0          py311ha68e1ae_0    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.9              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipfile-deflate64         0.2.0           py311ha68e1ae_4    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge
```

**Comment by haasad** [comment]
Please open a new issue for cases like this (ideally with a reference to the old one). It's just coincidence if somebody looks at or notices comment in old closed issues.

You can have multiple installations of the AB side by side using different conda environments. You can try something like this:
```
conda deactivate
conda create -n ab2 -c conda-forge --solver libmamba activity-browser
conda activate ab2
activity-browser
```
