### ISSUE TITLE
Issue while creating Activity Parameter

### ISSUE THREAD

**Issue by nabilahmed739** [LCA-ActivityBrowser/activity-browser#812]
I got an error while creating Activity Parameter, strangely it only happens in one of the activities.

Environment: Windows | AB version 2.6.9

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 3197, in execute_sql
>     cursor.execute(sql, params or ())
> sqlite3.IntegrityError: Cross group activity
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\activity_browser\controllers\parameter.py", line 49, in add_parameter
>     bw.parameters.new_activity_parameters([data], group)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\bw2data\parameters.py", line 1385, in new_activity_parameters
>     ActivityParameter.insert_many(data[idx:idx+100]).execute()
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 1927, in inner
>     return method(self, database, *args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 1998, in execute
>     return self._execute(database)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 2798, in _execute
>     return super(Insert, self)._execute(database)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 2511, in _execute
>     cursor = database.execute(self)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 3210, in execute
>     return self.execute_sql(sql, params, commit=commit)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 3204, in execute_sql
>     self.commit()
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 2970, in __exit__
>     reraise(new_type, new_type(exc_value, *exc_args), traceback)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 191, in reraise
>     raise value.with_traceback(tb)
>   File "C:\ProgramData\Anaconda3\envs\ab_premise\lib\site-packages\peewee.py", line 3197, in execute_sql
>     cursor.execute(sql, params or ())
> peewee.IntegrityError: Cross group activity

**Comment by MaximeAgez** [comment]
Sorry if it's evident, but did you check if there was anything weird happening in the parameters.db file? There might be something fishy happening in the activityparameter table or the group_table table, like having two different parameter groups for a single activity.

The parameters.db file is in .../AppData/Local/pylca/Brightway3/
