### ISSUE TITLE
Characterization factors not showing from treeview in Impact Categories

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#831]
While a double-click on an impact category from the treeview should open the characterization factors tab, I only get an error message (it does work from the listview): 

Qt Version: 5.12.9
```
Traceback (most recent call last):
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\layouts\tabs\impact_categories.py", line 151, in open_method_tab
    new_tab = CFsTab(self, method)
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\layouts\tabs\impact_categories.py", line 30, in __init__
    self.cf_table.model.sync(method)
  File "C:\Users\steub\surfdrive\Leiden\python\GitHub\LCA-ActivityBrowser\activity-browser\activity_browser\ui\tables\models\impact_categories.py", line 88, in sync
    self.build_row(obj) for obj in self.method.load()
  File "C:\Users\steub\miniconda3\envs\ab38\lib\site-packages\bw2data\data_store.py", line 86, in load
    raise UnknownObject("This object is not registered and has no data")
bw2data.errors.UnknownObject: This object is not registered and has no data
```

**Comment by bsteubing** [comment]
Further the tab where I get the CFs is somehow messed up right now...
![image](https://user-images.githubusercontent.com/33026150/187531911-0e013e9a-037d-4686-a1e3-0a4af9460f01.png)

**Comment by marc-vdm** [comment]
Similar problems as in #566
