### ISSUE TITLE
Missing numpy arrays in scenario calculations

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#883]
I tried the LCA calculation in the stable version of ab (v 2.6.9). Unfortunately, the same error occurred. An update of bw2io from 0.8.6. to 0.8.7 did not help either.
For me the error is the following:

```
Reset project settings directory to: C:\Users\...\AppData\Local\pylca\Brightway3\ei38.94dba3689598beaa9c370db13f6b8c45
Reset metadata.
Loaded project: ei38
Loading Scenario file. This may take a while for large files
Traceback (most recent call last):
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 58, in generate_setup
    new_tab = LCAResultsSubTab(data, self)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 103, in __init__
    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\activity_browser\bwutils\calculations.py", line 37, in do_LCA_calculations
    mlca = SuperstructureMLCA(cs_name, df)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\mlca.py", line 33, in __init__
    super().__init__(cs_name)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\activity_browser\bwutils\multilca.py", line 124, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\bw2calc\lca.py", line 338, in lci
    self.load_lci_data(builder=builder)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\bw2calc\lca.py", line 217, in load_lci_data
    builder.build(self.database_filepath)
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\bw2calc\matrices.py", line 143, in build
    array = load_arrays(paths)
  File "C:\Users\.........\mambaforge-data\envs\ab\lib\site-packages\bw2calc\utils.py", line 35, in load_arrays
    arrays.append(np.load(obj, allow_pickle=True))
  File "C:\Users\...\mambaforge-data\envs\ab\lib\site-packages\numpy\lib\npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\AppData\\Local\\pylca\\Brightway3\\ei38.94dba3689598beaa9c370db13f6b8c45\\processed\\comm_steel_SS_image_2020_2050.9e1a229e02575f563cde7670c96ecbd2.npy'
```

_Originally posted by @CHarpprecht in https://github.com/LCA-ActivityBrowser/activity-browser/issues/855#issuecomment-1323995109_

**Comment by marc-vdm** [comment]
Also happened here:
https://github.com/LCA-ActivityBrowser/activity-browser/pull/855#issuecomment-1288065249

**Comment by CHarpprecht** [comment]
@marc-vdm, 
I also tried again creating another superstructure with slightly modified processes. During the creation of the superstructure with premise, the AB was not running to ensure that no cross-talk between DBs or any DB-writing error could occur. 
However, this did not help. I got the same error:

```
Reset project settings directory to: C:\Users\...\Brightway3\ei38.94dba3689598beaa9c370db13f6b8c45
Reset metadata.
Loaded project: ei38
Current shape and databases in the MetaDataStore: (0, 0) set()
Adding: comm_steel_2_SS_image_2020_2050
Pandas Dataframe passed to sync. (82, 5)
+showing tab: Activity Details
+showing tab: Activity Details
New calculation setup: ss_steel2
Pandas Dataframe passed to sync. (6517, 5)
Pandas Dataframe passed to sync. (418, 5)
Pandas Dataframe passed to sync. (1, 5)
Dropevent from: <activity_browser.ui.tables.inventory.ActivitiesBiosphereTable(0x2cb768e1b40) at 0x000002CB765A26C0>
C:\Users...\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py:151: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._dataframe = self._dataframe.append(data, ignore_index=True)
C:\Users...\lib\site-packages\activity_browser\ui\tables\models\lca_setup.py:201: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._dataframe = self._dataframe.append(data, ignore_index=True)
Loading Scenario file. This may take a while for large files
Traceback (most recent call last):
  File "C:\Users...\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tab.py", line 56, in generate_setup
    new_tab = LCAResultsSubTab(data, self)
  File "C:\Users...\lib\site-packages\activity_browser\layouts\tabs\LCA_results_tabs.py", line 103, in __init__
    self.mlca, self.contributions, self.mc = calculations.do_LCA_calculations(data)
  File "C:\Users...\lib\site-packages\activity_browser\bwutils\calculations.py", line 24, in do_LCA_calculations
    mlca = SuperstructureMLCA(cs_name, df)
  File "C:\Users...\lib\site-packages\activity_browser\bwutils\superstructure\mlca.py", line 33, in __init__
    super().__init__(cs_name)
  File "C:\Users...\lib\site-packages\activity_browser\bwutils\multilca.py", line 124, in __init__
    self.lca.lci(factorize=True)
  File "C:\Users...\lib\site-packages\bw2calc\lca.py", line 338, in lci
    self.load_lci_data(builder=builder)
  File "C:\Users...\lib\site-packages\bw2calc\lca.py", line 217, in load_lci_data
    builder.build(self.database_filepath)
  File "C:\Users...\lib\site-packages\bw2calc\matrices.py", line 143, in build
    array = load_arrays(paths)
  File "C:\Users...\lib\site-packages\bw2calc\utils.py", line 35, in load_arrays
    arrays.append(np.load(obj, allow_pickle=True))
  File "C:\Users...\lib\site-packages\numpy\lib\npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users...\\pylca\\Brightway3\\ei38.94dba3689598beaa9c370db13f6b8c45\\processed\\comm_steel_2_SS_image_2020_2050.33a37f530833099abea946ab577b3005.npy'
```

This was in an environment with:
activity-browser-dev      2022.11.16                 
brightway2                2.4.2                      
bw2analyzer               0.10                    
bw2calc                   1.8.1                   
bw2data                   3.6.5                   
bw2io                     0.8.7                      
bw2parameters             0.7                       
bw_migrations             0.1

**Comment by marc-vdm** [comment]
@romainsacchi, As checked by @CHarpprecht, this doesn't seem to be caused by our latest update on this (#855), could this be related to changes in Premise? Or would you have ideas what else it could be?

**Comment by romainsacchi** [comment]
@CHarpprecht, could you try with a regular (non-superstructure) premise database? Do we think this is happening only with superstructure databases?

**Comment by romainsacchi** [comment]
It is very likely that `premise` is the cause, and it seems to concern superstructure databases only.
But if it indeed is, the fact that `activity-browser` remains silent about this is problematic. There should be extensive checking on both the db and the sdf (fields, values, types, etc.), with explicit error description when doing scenario LCA. Because it is otherwise going to be time-consuming to find where the error lies without any indication or obvious pattern.

**Comment by marc-vdm** [comment]
Agree that we need better error reporting with scenarios. Though I think the present error is a BW thing that happens during calculation, I'm not sure it's possible for us to detect this before BW does, IIRC we don't generate such `.npy` arrays on AB side. 

We (well.. @Zoophobus mostly) are also working on a better file format for importing sdf. Maybe we can tackle this both at the same time.

A challenge is that some checks are done on loading the sdf, and some checks are only done when executing calculation (as users can change other parts of the calc-setup after having loaded a file). It would maybe be better if we do all of this in one go.

@romainsacchi in an ideal world, what exact information would you like to get from AB when there are problems with a file? We can see on our side how much/if that is achievable.

Either way, I think we should perform checks and then provide a popup (wizard) that explains some problems, and then allows for exporting an error log or something. Though this would be quite some work to set up properly. I'm also thinking that we could add a `verify compatibility` button next to `calculate` that runs checks so user doesn't need to calculate -and when user ignores this, we still check before calculating-?


I think doing the below would be a good start:
- [ ] Identify all potential break-points in AB
- [ ] Move all checks/break-points to 1 moment (I think when user presses `calculate`, so the calculation setup is 'definitive')
- [ ] Gather a log of notable information for user
  - Automatically handled problems:
    - Removed duplicate flows
    - Production/technosphere flow collisions 
    - Missing keys gathered
    - Other...?
  - Unfixed problems (which still allow AB to run):
    - Do these problems exist?
    - Tell user that results may not be what they want because of these unfixed errors
  - Breaking problems:
    - What kinds of problems are these?
    - Tell user where the problem is, and potentially how to fix it
- [ ] Provide user with log summary and option to get access to full log?

**Comment by romainsacchi** [comment]
Sure, it's a lot of work. But getting a report when the sdf is wrongly formatted, has missing columns, wrong keys and any other things like that would be super useful.
@CHarpprecht can you send me your sdf + db?

**Comment by marc-vdm** [comment]
Alright, if you have ideas for us on what to show, please let me know, as you're probably the single most active user of the functionality haha.

We'll implement, just knowing better what you'd like to see will help us with that.

**Comment by Zoophobus** [comment]
Hi Marc-vdm and romainsacchi

sorry I haven't been more active in this issue, I have been looking at some other importer aspects. However this is probably the best place to take this forward.

> Move all checks/break-points to 1 moment (I think when user presses calculate, so the calculation setup is 'definitive')
So I'm against this, for me there should be two types of errors that we anticipate: 
The first type being all the obvious ones, basically what the external software (including the AB) explicitly identifies as errors, like !#NUM in excel, or NaNs. These I'd like to deal with on importing.

The second type being less obvious (like problematic keys, duplicates, ...).


My first reason for separating these out is down to the amount of processing that's required. For the explicit errors these are possible to determine rapidly upon loading. Essentially these I would identify as file import errors.

The other reason I'd like to keep these separated is because it could help us to make the code structure more explicit. I would be much happier if we can separate out some of the error checking functionality. So that we can keep individual classes/objects smaller and easier to understand
