### ISSUE TITLE
AB browser not installing on Mac Ventura 13.1

### ISSUE THREAD

**Issue by yannicfischer** [LCA-ActivityBrowser/activity-browser#961]
Hi, 

I have the following issue: wehen I try to install the AB with the following command 

conda create -n ab activity-browser

I get an error message: 

(base) yannic@MacBook-Pro-2 ~ % conda create -n ab activity-browser
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 379, in _load
        return self._load()
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 315, in _load
        cache.load_state()  # XXX should this succeed even if FileNotFound?
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 570, in load_state
        self.load(state_only=True)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 528, in load
        state = json.loads(state_file.read())
      File "/Users/yannic/anaconda3/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/Users/yannic/anaconda3/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/yannic/anaconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /Users/yannic/anaconda3/bin/conda create -n ab activity-browser`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/yannic/anaconda3/bin/conda
             CONDA_PREFIX=/Users/yannic/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/yannic/anaconda3/bin/python
               CONDA_ROOT=/Users/yannic/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/Users/yannic/anaconda3/bin:/Users/yannic/anaconda3/condabin:/Library/
                          Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Pyth
                          on.framework/Versions/3.8/bin:/usr/local/bin:/System/Cryptexes/App/usr
                          /bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/yannic/anaconda3
            shell level : 1
       user config file : /Users/yannic/.condarc
 populated config files : /Users/yannic/.condarc
          conda version : 23.3.1
    conda-build version : 3.23.3
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/yannic/anaconda3  (writable)
      conda av data dir : /Users/yannic/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/cmutel/osx-64
                          https://conda.anaconda.org/cmutel/noarch
                          https://conda.anaconda.org/bsteubing/osx-64
                          https://conda.anaconda.org/bsteubing/noarch
                          https://conda.anaconda.org/haasad/osx-64
                          https://conda.anaconda.org/haasad/noarch
                          https://conda.anaconda.org/pascallesage/osx-64
                          https://conda.anaconda.org/pascallesage/noarch
          package cache : /Users/yannic/anaconda3/pkgs
                          /Users/yannic/.conda/pkgs
       envs directories : /Users/yannic/anaconda3/envs
                          /Users/yannic/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Darwin/22.2.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 

I can not seem to find the issue. Any advice is much appreciated! Thanks in advance!

Kind regards
Yannic

**Comment by Zoophobus** [comment]
Hi @yannicfischer 

I was wondering if you've also tried the new installation procedure? In your case this will probably require changing the conda channels that have been allowed. So you'll need to run the following before you try installing the AB from conda-forge:

`conda config --remove channels cmutel
conda config --remove channels bsteubing
conda config --remove channels haasad
conda config --remove channels pascallesage`

best,
Jon

**Comment by yannicfischer** [comment]
Hi Jon, 

thanks for your answer. 
What do you mean by new installation procedure? Do you mean this: https://github.com/LCA-ActivityBrowser/activity-browser ?

I followed both ways, the quick and thorough one. Neither one worked. Before I tried the quick way I ran the code you provided. This is the report following the quick way:

(base) yannic@MacBook-Pro-2 ~ % conda create -n ab -c conda-forge activity-browser
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/Users/yannic/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 315, in _load
        cache.load_state()  # XXX should this succeed even if FileNotFound?
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 570, in load_state
        self.load(state_only=True)
      File "/Users/yannic/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 528, in load
        state = json.loads(state_file.read())
      File "/Users/yannic/anaconda3/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/Users/yannic/anaconda3/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/yannic/anaconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /Users/yannic/anaconda3/bin/conda create -n ab -c conda-forge activity-browser`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/yannic/anaconda3/bin/conda
             CONDA_PREFIX=/Users/yannic/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/yannic/anaconda3/bin/python
               CONDA_ROOT=/Users/yannic/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/Users/yannic/anaconda3/bin:/Users/yannic/anaconda3/condabin:/Library/
                          Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Pyth
                          on.framework/Versions/3.8/bin:/usr/local/bin:/System/Cryptexes/App/usr
                          /bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/yannic/anaconda3
            shell level : 1
       user config file : /Users/yannic/.condarc
 populated config files : /Users/yannic/.condarc
          conda version : 23.3.1
    conda-build version : 3.23.3
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.1=0
                          __unix=0=0
       base environment : /Users/yannic/anaconda3  (writable)
      conda av data dir : /Users/yannic/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/yannic/anaconda3/pkgs
                          /Users/yannic/.conda/pkgs
       envs directories : /Users/yannic/anaconda3/envs
                          /Users/yannic/.conda/envs
               platform : osx-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Darwin/22.2.0 OSX/13.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.

Thanks, 
Yannic

**Comment by Zoophobus** [comment]
Hi Yannic,

Hmmm, this might be a problem with conda. I'm not sure why it is failing to get the package meta-data. However, in the later case where it's grabbing the data (I assume) from conda-forge it does seem to work, which is a relief.

So a further question, or two. Are you having similar difficulties with installing other software with conda too? (e.g. is this a very specific problem for the AB?) Secondly, would you be willing to use mamba (a similar program to conda for resolving the dependencies, just much quicker)? You can install it using `conda install mamba`.

This might be related to this previous issue, however I'm not sure and would need to have a chat with our colleagues/collaborators (https://github.com/LCA-ActivityBrowser/activity-browser/issues/953#issue-1632301021)

**Comment by yannicfischer** [comment]
If that helps I am totally ok with using mama. How do I have to proceed?

**Comment by Zoophobus** [comment]
you should go to the base conda environment and try to install it there using the `conda install mamba` command.

**Comment by Zoophobus** [comment]
I should warn you though that there may be conflicts while you're installing mamba, especially if the base environment already has quite a few packages installed. You can try and resolve this by using following these instructions (https://stackoverflow.com/questions/62060079/how-to-solve-package-conflict-on-conda), or by wiping and reinstalling anaconda (which is what I have previously done in a windows environment)

**Comment by Zoophobus** [comment]
If you want any help in going through this then please feel free to contact me!

Best,
Jon

**Comment by Zoophobus** [comment]
@yannicfischer so in relation to this issue https://github.com/LCA-ActivityBrowser/activity-browser/issues/950#issue-1620479425 what I ended up doing on my computer (Linux) is remove the anaconda installation (without removing my environments, which I'd set up outside of the anaconda installation) and use miniconda instead. Then I installed mamba inside the base environment of miniconda.

Now it's much quicker for installing the AB, hopefully it's the same for you

**Comment by Zoophobus** [comment]
@yannicfischer thinking about this a little this might be better if you specify python=3.9* in the installation. There are some issues with the AB and the python versions >=3.10 in Linux

**Comment by Zoophobus** [comment]
@yannicfischer any updates on this?

**Comment by Zoophobus** [comment]
If you still have a problem feel free to reopen this @yannicfischer
